//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.06 at 02:28:38 AM CET 
//


package rs.ac.uns.ftn.portal_poverenika.model.resenje;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.portal_poverenika.model.resenje package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TAdresaBroj_QNAME = new QName("http://www.ftn.uns.ac.rs/types", "broj");
    private final static QName _TAdresaUlica_QNAME = new QName("http://www.ftn.uns.ac.rs/types", "ulica");
    private final static QName _TAdresaMesto_QNAME = new QName("http://www.ftn.uns.ac.rs/types", "mesto");
    private final static QName _TTekstP_QNAME = new QName("http://www.ftn.uns.ac.rs/types", "p");
    private final static QName _TFizickoLicePotpis_QNAME = new QName("http://www.ftn.uns.ac.rs/types", "potpis");
    private final static QName _TFizickoLiceIme_QNAME = new QName("http://www.ftn.uns.ac.rs/types", "ime");
    private final static QName _TFizickoLicePrezime_QNAME = new QName("http://www.ftn.uns.ac.rs/types", "prezime");
    private final static QName _TFizickoLiceDrugiPodaciZaKontakt_QNAME = new QName("http://www.ftn.uns.ac.rs/types", "drugi_podaci_za_kontakt");
    private final static QName _TFizickoLiceAdresa_QNAME = new QName("http://www.ftn.uns.ac.rs/types", "adresa");
    private final static QName _TInformacijeOResenjuBrojResenja_QNAME = new QName("http://www.ftn.uns.ac.rs/resenje", "broj_resenja");
    private final static QName _TInformacijeOResenjuDatumResenja_QNAME = new QName("http://www.ftn.uns.ac.rs/resenje", "datum_resenja");
    private final static QName _TInformacijeOResenjuDatumPodnosenjaZahteva_QNAME = new QName("http://www.ftn.uns.ac.rs/resenje", "datum_podnosenja_zahteva");
    private final static QName _TInformacijeOResenjuPodnosilacZahteva_QNAME = new QName("http://www.ftn.uns.ac.rs/resenje", "podnosilac_zahteva");
    private final static QName _TInformacijeOResenjuVrstaResenja_QNAME = new QName("http://www.ftn.uns.ac.rs/resenje", "vrsta_resenja");
    private final static QName _TInformacijeOResenjuOrgan_QNAME = new QName("http://www.ftn.uns.ac.rs/resenje", "organ");
    private final static QName _TPravnoLiceNazivOrgana_QNAME = new QName("http://www.ftn.uns.ac.rs/types", "naziv_organa");
    private final static QName _TSadrzajResenjaOpisResenja_QNAME = new QName("http://www.ftn.uns.ac.rs/resenje", "opis_resenja");
    private final static QName _TSadrzajResenjaObrazlozenje_QNAME = new QName("http://www.ftn.uns.ac.rs/resenje", "obrazlozenje");
    private final static QName _TSadrzajResenjaTeloResenja_QNAME = new QName("http://www.ftn.uns.ac.rs/resenje", "telo_resenja");
    private final static QName _TMestoDatumDatum_QNAME = new QName("http://www.ftn.uns.ac.rs/types", "datum");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.portal_poverenika.model.resenje
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TPravnoLice }
     * 
     */
    public TPravnoLice createTPravnoLice() {
        return new TPravnoLice();
    }

    /**
     * Create an instance of {@link TAdresa }
     * 
     */
    public TAdresa createTAdresa() {
        return new TAdresa();
    }

    /**
     * Create an instance of {@link TMestoDatum }
     * 
     */
    public TMestoDatum createTMestoDatum() {
        return new TMestoDatum();
    }

    /**
     * Create an instance of {@link TTekst }
     * 
     */
    public TTekst createTTekst() {
        return new TTekst();
    }

    /**
     * Create an instance of {@link TFizickoLice }
     * 
     */
    public TFizickoLice createTFizickoLice() {
        return new TFizickoLice();
    }

    /**
     * Create an instance of {@link TInformacijeOResenju }
     * 
     */
    public TInformacijeOResenju createTInformacijeOResenju() {
        return new TInformacijeOResenju();
    }

    /**
     * Create an instance of {@link Resenje }
     * 
     */
    public Resenje createResenje() {
        return new Resenje();
    }

    /**
     * Create an instance of {@link TSadrzajResenja }
     * 
     */
    public TSadrzajResenja createTSadrzajResenja() {
        return new TSadrzajResenja();
    }

    /**
     * Create an instance of {@link TId }
     * 
     */
    public TId createTId() {
        return new TId();
    }

    /**
     * Create an instance of {@link TPravnoLice.NazivOrgana }
     * 
     */
    public TPravnoLice.NazivOrgana createTPravnoLiceNazivOrgana() {
        return new TPravnoLice.NazivOrgana();
    }

    /**
     * Create an instance of {@link TAdresa.Mesto }
     * 
     */
    public TAdresa.Mesto createTAdresaMesto() {
        return new TAdresa.Mesto();
    }

    /**
     * Create an instance of {@link TAdresa.Ulica }
     * 
     */
    public TAdresa.Ulica createTAdresaUlica() {
        return new TAdresa.Ulica();
    }

    /**
     * Create an instance of {@link TAdresa.Broj }
     * 
     */
    public TAdresa.Broj createTAdresaBroj() {
        return new TAdresa.Broj();
    }

    /**
     * Create an instance of {@link TMestoDatum.Mesto }
     * 
     */
    public TMestoDatum.Mesto createTMestoDatumMesto() {
        return new TMestoDatum.Mesto();
    }

    /**
     * Create an instance of {@link TMestoDatum.Datum }
     * 
     */
    public TMestoDatum.Datum createTMestoDatumDatum() {
        return new TMestoDatum.Datum();
    }

    /**
     * Create an instance of {@link TTekst.P }
     * 
     */
    public TTekst.P createTTekstP() {
        return new TTekst.P();
    }

    /**
     * Create an instance of {@link TFizickoLice.Ime }
     * 
     */
    public TFizickoLice.Ime createTFizickoLiceIme() {
        return new TFizickoLice.Ime();
    }

    /**
     * Create an instance of {@link TFizickoLice.Prezime }
     * 
     */
    public TFizickoLice.Prezime createTFizickoLicePrezime() {
        return new TFizickoLice.Prezime();
    }

    /**
     * Create an instance of {@link TFizickoLice.DrugiPodaciZaKontakt }
     * 
     */
    public TFizickoLice.DrugiPodaciZaKontakt createTFizickoLiceDrugiPodaciZaKontakt() {
        return new TFizickoLice.DrugiPodaciZaKontakt();
    }

    /**
     * Create an instance of {@link TInformacijeOResenju.VrstaResenja }
     * 
     */
    public TInformacijeOResenju.VrstaResenja createTInformacijeOResenjuVrstaResenja() {
        return new TInformacijeOResenju.VrstaResenja();
    }

    /**
     * Create an instance of {@link TInformacijeOResenju.BrojResenja }
     * 
     */
    public TInformacijeOResenju.BrojResenja createTInformacijeOResenjuBrojResenja() {
        return new TInformacijeOResenju.BrojResenja();
    }

    /**
     * Create an instance of {@link TInformacijeOResenju.DatumResenja }
     * 
     */
    public TInformacijeOResenju.DatumResenja createTInformacijeOResenjuDatumResenja() {
        return new TInformacijeOResenju.DatumResenja();
    }

    /**
     * Create an instance of {@link TInformacijeOResenju.DatumPodnosenjaZahteva }
     * 
     */
    public TInformacijeOResenju.DatumPodnosenjaZahteva createTInformacijeOResenjuDatumPodnosenjaZahteva() {
        return new TInformacijeOResenju.DatumPodnosenjaZahteva();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TAdresa.Broj }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "broj", scope = TAdresa.class)
    public JAXBElement<TAdresa.Broj> createTAdresaBroj(TAdresa.Broj value) {
        return new JAXBElement<TAdresa.Broj>(_TAdresaBroj_QNAME, TAdresa.Broj.class, TAdresa.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TAdresa.Ulica }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "ulica", scope = TAdresa.class)
    public JAXBElement<TAdresa.Ulica> createTAdresaUlica(TAdresa.Ulica value) {
        return new JAXBElement<TAdresa.Ulica>(_TAdresaUlica_QNAME, TAdresa.Ulica.class, TAdresa.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TAdresa.Mesto }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "mesto", scope = TAdresa.class)
    public JAXBElement<TAdresa.Mesto> createTAdresaMesto(TAdresa.Mesto value) {
        return new JAXBElement<TAdresa.Mesto>(_TAdresaMesto_QNAME, TAdresa.Mesto.class, TAdresa.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTekst.P }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "p", scope = TTekst.class)
    public JAXBElement<TTekst.P> createTTekstP(TTekst.P value) {
        return new JAXBElement<TTekst.P>(_TTekstP_QNAME, TTekst.P.class, TTekst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "potpis", scope = TFizickoLice.class)
    public JAXBElement<String> createTFizickoLicePotpis(String value) {
        return new JAXBElement<String>(_TFizickoLicePotpis_QNAME, String.class, TFizickoLice.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TFizickoLice.Ime }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "ime", scope = TFizickoLice.class)
    public JAXBElement<TFizickoLice.Ime> createTFizickoLiceIme(TFizickoLice.Ime value) {
        return new JAXBElement<TFizickoLice.Ime>(_TFizickoLiceIme_QNAME, TFizickoLice.Ime.class, TFizickoLice.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TFizickoLice.Prezime }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "prezime", scope = TFizickoLice.class)
    public JAXBElement<TFizickoLice.Prezime> createTFizickoLicePrezime(TFizickoLice.Prezime value) {
        return new JAXBElement<TFizickoLice.Prezime>(_TFizickoLicePrezime_QNAME, TFizickoLice.Prezime.class, TFizickoLice.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TFizickoLice.DrugiPodaciZaKontakt }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "drugi_podaci_za_kontakt", scope = TFizickoLice.class)
    public JAXBElement<TFizickoLice.DrugiPodaciZaKontakt> createTFizickoLiceDrugiPodaciZaKontakt(TFizickoLice.DrugiPodaciZaKontakt value) {
        return new JAXBElement<TFizickoLice.DrugiPodaciZaKontakt>(_TFizickoLiceDrugiPodaciZaKontakt_QNAME, TFizickoLice.DrugiPodaciZaKontakt.class, TFizickoLice.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TAdresa }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "adresa", scope = TFizickoLice.class)
    public JAXBElement<TAdresa> createTFizickoLiceAdresa(TAdresa value) {
        return new JAXBElement<TAdresa>(_TFizickoLiceAdresa_QNAME, TAdresa.class, TFizickoLice.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TInformacijeOResenju.BrojResenja }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenje", name = "broj_resenja", scope = TInformacijeOResenju.class)
    public JAXBElement<TInformacijeOResenju.BrojResenja> createTInformacijeOResenjuBrojResenja(TInformacijeOResenju.BrojResenja value) {
        return new JAXBElement<TInformacijeOResenju.BrojResenja>(_TInformacijeOResenjuBrojResenja_QNAME, TInformacijeOResenju.BrojResenja.class, TInformacijeOResenju.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TInformacijeOResenju.DatumResenja }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenje", name = "datum_resenja", scope = TInformacijeOResenju.class)
    public JAXBElement<TInformacijeOResenju.DatumResenja> createTInformacijeOResenjuDatumResenja(TInformacijeOResenju.DatumResenja value) {
        return new JAXBElement<TInformacijeOResenju.DatumResenja>(_TInformacijeOResenjuDatumResenja_QNAME, TInformacijeOResenju.DatumResenja.class, TInformacijeOResenju.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TInformacijeOResenju.DatumPodnosenjaZahteva }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenje", name = "datum_podnosenja_zahteva", scope = TInformacijeOResenju.class)
    public JAXBElement<TInformacijeOResenju.DatumPodnosenjaZahteva> createTInformacijeOResenjuDatumPodnosenjaZahteva(TInformacijeOResenju.DatumPodnosenjaZahteva value) {
        return new JAXBElement<TInformacijeOResenju.DatumPodnosenjaZahteva>(_TInformacijeOResenjuDatumPodnosenjaZahteva_QNAME, TInformacijeOResenju.DatumPodnosenjaZahteva.class, TInformacijeOResenju.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TFizickoLice }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenje", name = "podnosilac_zahteva", scope = TInformacijeOResenju.class)
    public JAXBElement<TFizickoLice> createTInformacijeOResenjuPodnosilacZahteva(TFizickoLice value) {
        return new JAXBElement<TFizickoLice>(_TInformacijeOResenjuPodnosilacZahteva_QNAME, TFizickoLice.class, TInformacijeOResenju.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TInformacijeOResenju.VrstaResenja }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenje", name = "vrsta_resenja", scope = TInformacijeOResenju.class)
    public JAXBElement<TInformacijeOResenju.VrstaResenja> createTInformacijeOResenjuVrstaResenja(TInformacijeOResenju.VrstaResenja value) {
        return new JAXBElement<TInformacijeOResenju.VrstaResenja>(_TInformacijeOResenjuVrstaResenja_QNAME, TInformacijeOResenju.VrstaResenja.class, TInformacijeOResenju.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TPravnoLice }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenje", name = "organ", scope = TInformacijeOResenju.class)
    public JAXBElement<TPravnoLice> createTInformacijeOResenjuOrgan(TPravnoLice value) {
        return new JAXBElement<TPravnoLice>(_TInformacijeOResenjuOrgan_QNAME, TPravnoLice.class, TInformacijeOResenju.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TPravnoLice.NazivOrgana }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "naziv_organa", scope = TPravnoLice.class)
    public JAXBElement<TPravnoLice.NazivOrgana> createTPravnoLiceNazivOrgana(TPravnoLice.NazivOrgana value) {
        return new JAXBElement<TPravnoLice.NazivOrgana>(_TPravnoLiceNazivOrgana_QNAME, TPravnoLice.NazivOrgana.class, TPravnoLice.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TAdresa }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "adresa", scope = TPravnoLice.class)
    public JAXBElement<TAdresa> createTPravnoLiceAdresa(TAdresa value) {
        return new JAXBElement<TAdresa>(_TFizickoLiceAdresa_QNAME, TAdresa.class, TPravnoLice.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTekst }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenje", name = "opis_resenja", scope = TSadrzajResenja.class)
    public JAXBElement<TTekst> createTSadrzajResenjaOpisResenja(TTekst value) {
        return new JAXBElement<TTekst>(_TSadrzajResenjaOpisResenja_QNAME, TTekst.class, TSadrzajResenja.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTekst }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenje", name = "obrazlozenje", scope = TSadrzajResenja.class)
    public JAXBElement<TTekst> createTSadrzajResenjaObrazlozenje(TTekst value) {
        return new JAXBElement<TTekst>(_TSadrzajResenjaObrazlozenje_QNAME, TTekst.class, TSadrzajResenja.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTekst }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenje", name = "telo_resenja", scope = TSadrzajResenja.class)
    public JAXBElement<TTekst> createTSadrzajResenjaTeloResenja(TTekst value) {
        return new JAXBElement<TTekst>(_TSadrzajResenjaTeloResenja_QNAME, TTekst.class, TSadrzajResenja.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TMestoDatum.Datum }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "datum", scope = TMestoDatum.class)
    public JAXBElement<TMestoDatum.Datum> createTMestoDatumDatum(TMestoDatum.Datum value) {
        return new JAXBElement<TMestoDatum.Datum>(_TMestoDatumDatum_QNAME, TMestoDatum.Datum.class, TMestoDatum.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TMestoDatum.Mesto }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "mesto", scope = TMestoDatum.class)
    public JAXBElement<TMestoDatum.Mesto> createTMestoDatumMesto(TMestoDatum.Mesto value) {
        return new JAXBElement<TMestoDatum.Mesto>(_TAdresaMesto_QNAME, TMestoDatum.Mesto.class, TMestoDatum.class, value);
    }

}
