//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.06 at 02:28:38 AM CET 
//


package rs.ac.uns.ftn.portal_poverenika.model.resenje;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;
import java.util.HashMap;
import java.util.Map;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="informacije_o_resenju" type="{http://www.ftn.uns.ac.rs/resenje}TInformacijeOResenju"/>
 *         &lt;element name="sadrzaj_resenja" type="{http://www.ftn.uns.ac.rs/resenje}TSadrzajResenja"/>
 *         &lt;element name="poverenik" type="{http://www.ftn.uns.ac.rs/types}TFizicko_Lice"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="userId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="datum" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="about" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="zalbaId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;anyAttribute processContents='lax'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "informacijeOResenju",
    "sadrzajResenja",
    "poverenik"
})
@XmlRootElement(name = "resenje", namespace = "http://www.ftn.uns.ac.rs/resenje")
public class Resenje {

    @XmlElement(name = "informacije_o_resenju", namespace = "http://www.ftn.uns.ac.rs/resenje", required = true)
    protected TInformacijeOResenju informacijeOResenju;
    @XmlElement(name = "sadrzaj_resenja", namespace = "http://www.ftn.uns.ac.rs/resenje", required = true)
    protected TSadrzajResenja sadrzajResenja;
    @XmlElement(namespace = "http://www.ftn.uns.ac.rs/resenje", required = true)
    protected TFIzickoLice poverenik;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "userId")
    protected String userId;
    @XmlAttribute(name = "datum")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datum;
    @XmlAttribute(name = "about")
    protected String about;
    @XmlAttribute(name = "zalbaId")
    protected String zalbaId;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the informacijeOResenju property.
     * 
     * @return
     *     possible object is
     *     {@link TInformacijeOResenju }
     *     
     */
    public TInformacijeOResenju getInformacijeOResenju() {
        return informacijeOResenju;
    }

    /**
     * Sets the value of the informacijeOResenju property.
     * 
     * @param value
     *     allowed object is
     *     {@link TInformacijeOResenju }
     *     
     */
    public void setInformacijeOResenju(TInformacijeOResenju value) {
        this.informacijeOResenju = value;
    }

    /**
     * Gets the value of the sadrzajResenja property.
     * 
     * @return
     *     possible object is
     *     {@link TSadrzajResenja }
     *     
     */
    public TSadrzajResenja getSadrzajResenja() {
        return sadrzajResenja;
    }

    /**
     * Sets the value of the sadrzajResenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSadrzajResenja }
     *     
     */
    public void setSadrzajResenja(TSadrzajResenja value) {
        this.sadrzajResenja = value;
    }

    /**
     * Gets the value of the poverenik property.
     * 
     * @return
     *     possible object is
     *     {@link TFIzickoLice }
     *     
     */
    public TFIzickoLice getPoverenik() {
        return poverenik;
    }

    /**
     * Sets the value of the poverenik property.
     * 
     * @param value
     *     allowed object is
     *     {@link TFIzickoLice }
     *     
     */
    public void setPoverenik(TFIzickoLice value) {
        this.poverenik = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the userId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserId(String value) {
        this.userId = value;
    }

    /**
     * Gets the value of the datum property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatum() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatum(XMLGregorianCalendar value) {
        this.datum = value;
    }

    /**
     * Gets the value of the about property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbout() {
        return about;
    }

    /**
     * Sets the value of the about property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbout(String value) {
        this.about = value;
    }

    /**
     * Gets the value of the zalbaId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZalbaId() {
        return zalbaId;
    }

    /**
     * Sets the value of the zalbaId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZalbaId(String value) {
        this.zalbaId = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
