//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.29 at 11:58:19 PM CET 
//


package rs.ac.uns.ftn.portal_organa_vlasti.model.zahtev;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.portal_organa_vlasti.model.zahtev package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TNacinDrugiNacin_QNAME = new QName("http://www.ftn.uns.ac.rs/zahtev", "drugi_nacin");
    private final static QName _TInformacijeSadrzajInformacija_QNAME = new QName("http://www.ftn.uns.ac.rs/zahtev", "sadrzaj_informacija");
    private final static QName _TZakonNapomena_QNAME = new QName("http://www.ftn.uns.ac.rs/zahtev", "napomena");
    private final static QName _TTekstP_QNAME = new QName("http://www.ftn.uns.ac.rs/types", "p");
    private final static QName _TAdresaBroj_QNAME = new QName("http://www.ftn.uns.ac.rs/types", "broj");
    private final static QName _TAdresaUlica_QNAME = new QName("http://www.ftn.uns.ac.rs/types", "ulica");
    private final static QName _TAdresaMesto_QNAME = new QName("http://www.ftn.uns.ac.rs/types", "mesto");
    private final static QName _TMestoDatumDatum_QNAME = new QName("http://www.ftn.uns.ac.rs/types", "datum");
    private final static QName _TPravnoLiceNazivOrgana_QNAME = new QName("http://www.ftn.uns.ac.rs/types", "naziv_organa");
    private final static QName _TPravnoLiceAdresa_QNAME = new QName("http://www.ftn.uns.ac.rs/types", "adresa");
    private final static QName _TZahtevListaNacina_QNAME = new QName("http://www.ftn.uns.ac.rs/zahtev", "lista_nacina");
    private final static QName _TFIzickoLicePotpis_QNAME = new QName("http://www.ftn.uns.ac.rs/types", "potpis");
    private final static QName _TFIzickoLiceIme_QNAME = new QName("http://www.ftn.uns.ac.rs/types", "ime");
    private final static QName _TFIzickoLicePrezime_QNAME = new QName("http://www.ftn.uns.ac.rs/types", "prezime");
    private final static QName _TFIzickoLiceDrugiPodaciZaKontakt_QNAME = new QName("http://www.ftn.uns.ac.rs/types", "drugi_podaci_za_kontakt");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.portal_organa_vlasti.model.zahtev
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TAdresa }
     * 
     */
    public TAdresa createTAdresa() {
        return new TAdresa();
    }

    /**
     * Create an instance of {@link TTekst }
     * 
     */
    public TTekst createTTekst() {
        return new TTekst();
    }

    /**
     * Create an instance of {@link TFIzickoLice }
     * 
     */
    public TFIzickoLice createTFIzickoLice() {
        return new TFIzickoLice();
    }

    /**
     * Create an instance of {@link TMestoDatum }
     * 
     */
    public TMestoDatum createTMestoDatum() {
        return new TMestoDatum();
    }

    /**
     * Create an instance of {@link TPravnoLice }
     * 
     */
    public TPravnoLice createTPravnoLice() {
        return new TPravnoLice();
    }

    /**
     * Create an instance of {@link DokumentZahtev }
     * 
     */
    public DokumentZahtev createDokumentZahtev() {
        return new DokumentZahtev();
    }

    /**
     * Create an instance of {@link TZakon }
     * 
     */
    public TZakon createTZakon() {
        return new TZakon();
    }

    /**
     * Create an instance of {@link TListaZahteva }
     * 
     */
    public TListaZahteva createTListaZahteva() {
        return new TListaZahteva();
    }

    /**
     * Create an instance of {@link TInformacije }
     * 
     */
    public TInformacije createTInformacije() {
        return new TInformacije();
    }

    /**
     * Create an instance of {@link TListaNapomena }
     * 
     */
    public TListaNapomena createTListaNapomena() {
        return new TListaNapomena();
    }

    /**
     * Create an instance of {@link TListaNacina }
     * 
     */
    public TListaNacina createTListaNacina() {
        return new TListaNacina();
    }

    /**
     * Create an instance of {@link TNapomena }
     * 
     */
    public TNapomena createTNapomena() {
        return new TNapomena();
    }

    /**
     * Create an instance of {@link TNacin }
     * 
     */
    public TNacin createTNacin() {
        return new TNacin();
    }

    /**
     * Create an instance of {@link TDrugiNacin }
     * 
     */
    public TDrugiNacin createTDrugiNacin() {
        return new TDrugiNacin();
    }

    /**
     * Create an instance of {@link TZahtev }
     * 
     */
    public TZahtev createTZahtev() {
        return new TZahtev();
    }

    /**
     * Create an instance of {@link TId }
     * 
     */
    public TId createTId() {
        return new TId();
    }

    /**
     * Create an instance of {@link TAdresa.Mesto }
     * 
     */
    public TAdresa.Mesto createTAdresaMesto() {
        return new TAdresa.Mesto();
    }

    /**
     * Create an instance of {@link TAdresa.Ulica }
     * 
     */
    public TAdresa.Ulica createTAdresaUlica() {
        return new TAdresa.Ulica();
    }

    /**
     * Create an instance of {@link TAdresa.Broj }
     * 
     */
    public TAdresa.Broj createTAdresaBroj() {
        return new TAdresa.Broj();
    }

    /**
     * Create an instance of {@link TTekst.P }
     * 
     */
    public TTekst.P createTTekstP() {
        return new TTekst.P();
    }

    /**
     * Create an instance of {@link TFIzickoLice.Ime }
     * 
     */
    public TFIzickoLice.Ime createTFIzickoLiceIme() {
        return new TFIzickoLice.Ime();
    }

    /**
     * Create an instance of {@link TFIzickoLice.Prezime }
     * 
     */
    public TFIzickoLice.Prezime createTFIzickoLicePrezime() {
        return new TFIzickoLice.Prezime();
    }

    /**
     * Create an instance of {@link TFIzickoLice.DrugiPodaciZaKontakt }
     * 
     */
    public TFIzickoLice.DrugiPodaciZaKontakt createTFIzickoLiceDrugiPodaciZaKontakt() {
        return new TFIzickoLice.DrugiPodaciZaKontakt();
    }

    /**
     * Create an instance of {@link TMestoDatum.Mesto }
     * 
     */
    public TMestoDatum.Mesto createTMestoDatumMesto() {
        return new TMestoDatum.Mesto();
    }

    /**
     * Create an instance of {@link TMestoDatum.Datum }
     * 
     */
    public TMestoDatum.Datum createTMestoDatumDatum() {
        return new TMestoDatum.Datum();
    }

    /**
     * Create an instance of {@link TPravnoLice.NazivOrgana }
     * 
     */
    public TPravnoLice.NazivOrgana createTPravnoLiceNazivOrgana() {
        return new TPravnoLice.NazivOrgana();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TDrugiNacin }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zahtev", name = "drugi_nacin", scope = TNacin.class)
    public JAXBElement<TDrugiNacin> createTNacinDrugiNacin(TDrugiNacin value) {
        return new JAXBElement<TDrugiNacin>(_TNacinDrugiNacin_QNAME, TDrugiNacin.class, TNacin.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zahtev", name = "sadrzaj_informacija", scope = TInformacije.class)
    public JAXBElement<String> createTInformacijeSadrzajInformacija(String value) {
        return new JAXBElement<String>(_TInformacijeSadrzajInformacija_QNAME, String.class, TInformacije.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TNapomena }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zahtev", name = "napomena", scope = TZakon.class)
    public JAXBElement<TNapomena> createTZakonNapomena(TNapomena value) {
        return new JAXBElement<TNapomena>(_TZakonNapomena_QNAME, TNapomena.class, TZakon.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTekst.P }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "p", scope = TTekst.class)
    public JAXBElement<TTekst.P> createTTekstP(TTekst.P value) {
        return new JAXBElement<TTekst.P>(_TTekstP_QNAME, TTekst.P.class, TTekst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TAdresa.Broj }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "broj", scope = TAdresa.class)
    public JAXBElement<TAdresa.Broj> createTAdresaBroj(TAdresa.Broj value) {
        return new JAXBElement<TAdresa.Broj>(_TAdresaBroj_QNAME, TAdresa.Broj.class, TAdresa.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TAdresa.Ulica }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "ulica", scope = TAdresa.class)
    public JAXBElement<TAdresa.Ulica> createTAdresaUlica(TAdresa.Ulica value) {
        return new JAXBElement<TAdresa.Ulica>(_TAdresaUlica_QNAME, TAdresa.Ulica.class, TAdresa.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TAdresa.Mesto }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "mesto", scope = TAdresa.class)
    public JAXBElement<TAdresa.Mesto> createTAdresaMesto(TAdresa.Mesto value) {
        return new JAXBElement<TAdresa.Mesto>(_TAdresaMesto_QNAME, TAdresa.Mesto.class, TAdresa.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TMestoDatum.Datum }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "datum", scope = TMestoDatum.class)
    public JAXBElement<TMestoDatum.Datum> createTMestoDatumDatum(TMestoDatum.Datum value) {
        return new JAXBElement<TMestoDatum.Datum>(_TMestoDatumDatum_QNAME, TMestoDatum.Datum.class, TMestoDatum.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TMestoDatum.Mesto }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "mesto", scope = TMestoDatum.class)
    public JAXBElement<TMestoDatum.Mesto> createTMestoDatumMesto(TMestoDatum.Mesto value) {
        return new JAXBElement<TMestoDatum.Mesto>(_TAdresaMesto_QNAME, TMestoDatum.Mesto.class, TMestoDatum.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TPravnoLice.NazivOrgana }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "naziv_organa", scope = TPravnoLice.class)
    public JAXBElement<TPravnoLice.NazivOrgana> createTPravnoLiceNazivOrgana(TPravnoLice.NazivOrgana value) {
        return new JAXBElement<TPravnoLice.NazivOrgana>(_TPravnoLiceNazivOrgana_QNAME, TPravnoLice.NazivOrgana.class, TPravnoLice.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TAdresa }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "adresa", scope = TPravnoLice.class)
    public JAXBElement<TAdresa> createTPravnoLiceAdresa(TAdresa value) {
        return new JAXBElement<TAdresa>(_TPravnoLiceAdresa_QNAME, TAdresa.class, TPravnoLice.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TListaNacina }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zahtev", name = "lista_nacina", scope = TZahtev.class)
    public JAXBElement<TListaNacina> createTZahtevListaNacina(TListaNacina value) {
        return new JAXBElement<TListaNacina>(_TZahtevListaNacina_QNAME, TListaNacina.class, TZahtev.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TNapomena }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zahtev", name = "napomena", scope = TZahtev.class)
    public JAXBElement<TNapomena> createTZahtevNapomena(TNapomena value) {
        return new JAXBElement<TNapomena>(_TZakonNapomena_QNAME, TNapomena.class, TZahtev.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "potpis", scope = TFIzickoLice.class)
    public JAXBElement<String> createTFIzickoLicePotpis(String value) {
        return new JAXBElement<String>(_TFIzickoLicePotpis_QNAME, String.class, TFIzickoLice.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TFIzickoLice.Ime }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "ime", scope = TFIzickoLice.class)
    public JAXBElement<TFIzickoLice.Ime> createTFIzickoLiceIme(TFIzickoLice.Ime value) {
        return new JAXBElement<TFIzickoLice.Ime>(_TFIzickoLiceIme_QNAME, TFIzickoLice.Ime.class, TFIzickoLice.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TFIzickoLice.Prezime }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "prezime", scope = TFIzickoLice.class)
    public JAXBElement<TFIzickoLice.Prezime> createTFIzickoLicePrezime(TFIzickoLice.Prezime value) {
        return new JAXBElement<TFIzickoLice.Prezime>(_TFIzickoLicePrezime_QNAME, TFIzickoLice.Prezime.class, TFIzickoLice.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TFIzickoLice.DrugiPodaciZaKontakt }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "drugi_podaci_za_kontakt", scope = TFIzickoLice.class)
    public JAXBElement<TFIzickoLice.DrugiPodaciZaKontakt> createTFIzickoLiceDrugiPodaciZaKontakt(TFIzickoLice.DrugiPodaciZaKontakt value) {
        return new JAXBElement<TFIzickoLice.DrugiPodaciZaKontakt>(_TFIzickoLiceDrugiPodaciZaKontakt_QNAME, TFIzickoLice.DrugiPodaciZaKontakt.class, TFIzickoLice.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TAdresa }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "adresa", scope = TFIzickoLice.class)
    public JAXBElement<TAdresa> createTFIzickoLiceAdresa(TAdresa value) {
        return new JAXBElement<TAdresa>(_TPravnoLiceAdresa_QNAME, TAdresa.class, TFIzickoLice.class, value);
    }

}
