//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.05 at 06:27:58 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(
        namespace = "http://www.ftn.uns.ac.rs/zahtev",
        elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
        location = "http://www.ftn.uns.ac.rs/zahtev ../xsd/zahtev.xsd",
        xmlns = {@XmlNs(prefix = "zah", namespaceURI = "http://www.ftn.uns.ac.rs/zahtev"),
                @XmlNs(prefix = "types", namespaceURI = "http://www.ftn.uns.ac.rs/types"),
                @XmlNs(prefix = "pred", namespaceURI = "http://examples/predicate/"),
                @XmlNs(prefix = "xsi", namespaceURI = "http://www.w3.org/2001/XMLSchema-instance")})
package rs.ac.uns.ftn.portal_organa_vlasti.model.zahtev;

import javax.xml.bind.annotation.XmlNs;