//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.12 at 12:43:42 AM CET
//

@javax.xml.bind.annotation.XmlSchema(
        namespace = "zahtev_za_pristup_informacijama",
        elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
        location = "zahtev_za_pristup_informacijama ../schemas/zahtev.xsd",
        xmlns = {@XmlNs(prefix = "zah",
                namespaceURI = "zahtev_za_pristup_informacijama"),
                @XmlNs(prefix = "pred", namespaceURI = "http://examples/predicate/"),
                @XmlNs(prefix = "xsi", namespaceURI = "http://www.w3.org/2001/XMLSchema-instance")})
package rs.ac.uns.ftn.portal_organa_vlasti.model.zahtev;

import javax.xml.bind.annotation.XmlNs;