//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.12 at 12:37:06 AM CET 
//


package rs.ac.uns.ftn.portal_poverenika.model.types;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import java.math.BigInteger;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TMestoDatumDatum_QNAME = new QName("", "datum");
    private final static QName _TMestoDatumMesto_QNAME = new QName("", "mesto");
    private final static QName _TLiceAdresa_QNAME = new QName("", "Adresa");
    private final static QName _TAdresaUlica_QNAME = new QName("", "ulica");
    private final static QName _TAdresaBroj_QNAME = new QName("", "broj");
    private final static QName _TTekstP_QNAME = new QName("", "p");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TTekst }
     * 
     */
    public TTekst createTTekst() {
        return new TTekst();
    }

    /**
     * Create an instance of {@link TMestoDatum }
     * 
     */
    public TMestoDatum createTMestoDatum() {
        return new TMestoDatum();
    }

    /**
     * Create an instance of {@link TAdresa }
     * 
     */
    public TAdresa createTAdresa() {
        return new TAdresa();
    }

    /**
     * Create an instance of {@link TPravnoLice }
     * 
     */
    public TPravnoLice createTPravnoLice() {
        return new TPravnoLice();
    }

    /**
     * Create an instance of {@link TFIzickoLice }
     * 
     */
    public TFIzickoLice createTFIzickoLice() {
        return new TFIzickoLice();
    }

    /**
     * Create an instance of {@link TId }
     * 
     */
    public TId createTId() {
        return new TId();
    }

    /**
     * Create an instance of {@link TTekst.P }
     * 
     */
    public TTekst.P createTTekstP() {
        return new TTekst.P();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "datum", scope = TMestoDatum.class)
    public JAXBElement<String> createTMestoDatumDatum(String value) {
        return new JAXBElement<String>(_TMestoDatumDatum_QNAME, String.class, TMestoDatum.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mesto", scope = TMestoDatum.class)
    public JAXBElement<String> createTMestoDatumMesto(String value) {
        return new JAXBElement<String>(_TMestoDatumMesto_QNAME, String.class, TMestoDatum.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TAdresa }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Adresa", scope = TLice.class)
    public JAXBElement<TAdresa> createTLiceAdresa(TAdresa value) {
        return new JAXBElement<TAdresa>(_TLiceAdresa_QNAME, TAdresa.class, TLice.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ulica", scope = TAdresa.class)
    public JAXBElement<String> createTAdresaUlica(String value) {
        return new JAXBElement<String>(_TAdresaUlica_QNAME, String.class, TAdresa.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "broj", scope = TAdresa.class)
    public JAXBElement<BigInteger> createTAdresaBroj(BigInteger value) {
        return new JAXBElement<BigInteger>(_TAdresaBroj_QNAME, BigInteger.class, TAdresa.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mesto", scope = TAdresa.class)
    public JAXBElement<String> createTAdresaMesto(String value) {
        return new JAXBElement<String>(_TMestoDatumMesto_QNAME, String.class, TAdresa.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTekst.P }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "p", scope = TTekst.class)
    public JAXBElement<TTekst.P> createTTekstP(TTekst.P value) {
        return new JAXBElement<TTekst.P>(_TTekstP_QNAME, TTekst.P.class, TTekst.class, value);
    }

}
