//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.06 at 02:26:58 AM CET 
//


package rs.ac.uns.ftn.portal_poverenika.model.zalba_protiv_cutanja;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="vrsta_zalbe" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="primalac_zalbe" type="{http://www.ftn.uns.ac.rs/types}TPravno_Lice"/>
 *         &lt;element name="informacije_o_zalbi" type="{http://www.ftn.uns.ac.rs/zalba_protiv_cutanja}TInformacije_o_zalbi"/>
 *         &lt;element name="lista_razloga" type="{http://www.ftn.uns.ac.rs/zalba_protiv_cutanja}TLista_razloga"/>
 *         &lt;element name="detalji_zalbe" type="{http://www.ftn.uns.ac.rs/zalba_protiv_cutanja}TDetalji_zalbe"/>
 *         &lt;element name="predlog_resenja" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="napomena" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="podnosilac_zalbe" type="{http://www.ftn.uns.ac.rs/types}TFizicko_Lice"/>
 *         &lt;element name="mesto_i_datum" type="{http://www.ftn.uns.ac.rs/types}TMesto_Datum"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="userId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="datum" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="about" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="zahtevId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="status" type="{http://www.ftn.uns.ac.rs/zalba_protiv_cutanja}status" />
 *       &lt;anyAttribute processContents='lax'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "zalba_protiv_cutanja", namespace = "http://www.ftn.uns.ac.rs/zalba_protiv_cutanja")
public class ZalbaProtivCutanja {

    @XmlElementRefs({
        @XmlElementRef(name = "napomena", namespace = "http://www.ftn.uns.ac.rs/zalba_protiv_cutanja", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "vrsta_zalbe", namespace = "http://www.ftn.uns.ac.rs/zalba_protiv_cutanja", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "lista_razloga", namespace = "http://www.ftn.uns.ac.rs/zalba_protiv_cutanja", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "predlog_resenja", namespace = "http://www.ftn.uns.ac.rs/zalba_protiv_cutanja", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "podnosilac_zalbe", namespace = "http://www.ftn.uns.ac.rs/zalba_protiv_cutanja", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "informacije_o_zalbi", namespace = "http://www.ftn.uns.ac.rs/zalba_protiv_cutanja", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "detalji_zalbe", namespace = "http://www.ftn.uns.ac.rs/zalba_protiv_cutanja", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "mesto_i_datum", namespace = "http://www.ftn.uns.ac.rs/zalba_protiv_cutanja", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "primalac_zalbe", namespace = "http://www.ftn.uns.ac.rs/zalba_protiv_cutanja", type = JAXBElement.class, required = false)
    })
    @XmlMixed
    protected List<Serializable> content;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "userId")
    protected String userId;
    @XmlAttribute(name = "datum")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datum;
    @XmlAttribute(name = "about")
    protected String about;
    @XmlAttribute(name = "zahtevId")
    protected String zahtevId;
    @XmlAttribute(name = "status")
    protected Status status;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link TListaRazloga }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link TFizickoLice }{@code >}
     * {@link JAXBElement }{@code <}{@link TInformacijeOZalbi }{@code >}
     * {@link JAXBElement }{@code <}{@link TDetaljiZalbe }{@code >}
     * {@link JAXBElement }{@code <}{@link TMestoDatum }{@code >}
     * {@link JAXBElement }{@code <}{@link TPravnoLice }{@code >}
     * {@link String }
     * 
     * 
     */
    public List<Serializable> getContent() {
        if (content == null) {
            content = new ArrayList<Serializable>();
        }
        return this.content;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the userId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserId(String value) {
        this.userId = value;
    }

    /**
     * Gets the value of the datum property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatum() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatum(XMLGregorianCalendar value) {
        this.datum = value;
    }

    /**
     * Gets the value of the about property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbout() {
        return about;
    }

    /**
     * Sets the value of the about property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbout(String value) {
        this.about = value;
    }

    /**
     * Gets the value of the zahtevId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZahtevId() {
        return zahtevId;
    }

    /**
     * Sets the value of the zahtevId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZahtevId(String value) {
        this.zahtevId = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link Status }
     *     
     */
    public Status getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link Status }
     *     
     */
    public void setStatus(Status value) {
        this.status = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
