//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.06 at 04:51:51 AM CET 
//


package rs.ac.uns.ftn.portal_poverenika.soap.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Notification complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Notification"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="pdfFile" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/&gt;
 *         &lt;element name="htmlFile" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/&gt;
 *         &lt;element name="receiverEmail" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="senderEmail" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="documentId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Notification", namespace = "http://www.ftn.uns.ac.rs/notification", propOrder = {
    "pdfFile",
    "htmlFile",
    "receiverEmail",
    "senderEmail",
    "documentId"
})
public class Notification {

    @XmlElement(namespace = "http://www.ftn.uns.ac.rs/notification", required = true)
    protected byte[] pdfFile;
    @XmlElement(namespace = "http://www.ftn.uns.ac.rs/notification", required = true)
    protected byte[] htmlFile;
    @XmlElement(namespace = "http://www.ftn.uns.ac.rs/notification", required = true)
    protected String receiverEmail;
    @XmlElement(namespace = "http://www.ftn.uns.ac.rs/notification", required = true)
    protected String senderEmail;
    @XmlElement(namespace = "http://www.ftn.uns.ac.rs/notification", required = true)
    protected String documentId;

    /**
     * Gets the value of the pdfFile property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getPdfFile() {
        return pdfFile;
    }

    /**
     * Sets the value of the pdfFile property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setPdfFile(byte[] value) {
        this.pdfFile = value;
    }

    /**
     * Gets the value of the htmlFile property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getHtmlFile() {
        return htmlFile;
    }

    /**
     * Sets the value of the htmlFile property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setHtmlFile(byte[] value) {
        this.htmlFile = value;
    }

    /**
     * Gets the value of the receiverEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiverEmail() {
        return receiverEmail;
    }

    /**
     * Sets the value of the receiverEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiverEmail(String value) {
        this.receiverEmail = value;
    }

    /**
     * Gets the value of the senderEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderEmail() {
        return senderEmail;
    }

    /**
     * Sets the value of the senderEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderEmail(String value) {
        this.senderEmail = value;
    }

    /**
     * Gets the value of the documentId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentId() {
        return documentId;
    }

    /**
     * Sets the value of the documentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentId(String value) {
        this.documentId = value;
    }

}
