//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.06 at 04:51:51 AM CET 
//


package rs.ac.uns.ftn.portal_poverenika.soap.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RejectNotification complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RejectNotification"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="zahtevId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="senderEmail" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="receiverEmail" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RejectNotification", namespace = "http://www.ftn.uns.ac.rs/reject_notification", propOrder = {
    "zahtevId",
    "senderEmail",
    "receiverEmail"
})
public class RejectNotification {

    @XmlElement(namespace = "http://www.ftn.uns.ac.rs/reject_notification", required = true)
    protected String zahtevId;
    @XmlElement(namespace = "http://www.ftn.uns.ac.rs/reject_notification", required = true)
    protected String senderEmail;
    @XmlElement(namespace = "http://www.ftn.uns.ac.rs/reject_notification", required = true)
    protected String receiverEmail;

    /**
     * Gets the value of the zahtevId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZahtevId() {
        return zahtevId;
    }

    /**
     * Sets the value of the zahtevId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZahtevId(String value) {
        this.zahtevId = value;
    }

    /**
     * Gets the value of the senderEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderEmail() {
        return senderEmail;
    }

    /**
     * Sets the value of the senderEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderEmail(String value) {
        this.senderEmail = value;
    }

    /**
     * Gets the value of the receiverEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiverEmail() {
        return receiverEmail;
    }

    /**
     * Sets the value of the receiverEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiverEmail(String value) {
        this.receiverEmail = value;
    }

}
