//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.06 at 04:51:51 AM CET 
//


package rs.ac.uns.ftn.portal_poverenika.soap.model.email;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.portal_poverenika.soap.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RejectZahtev_QNAME = new QName("http://soap.email_service.ftn.uns.ac.rs/", "rejectZahtev");
    private final static QName _RejectZahtevResponse_QNAME = new QName("http://soap.email_service.ftn.uns.ac.rs/", "rejectZahtevResponse");
    private final static QName _SendObavestenje_QNAME = new QName("http://soap.email_service.ftn.uns.ac.rs/", "sendObavestenje");
    private final static QName _SendObavestenjeResponse_QNAME = new QName("http://soap.email_service.ftn.uns.ac.rs/", "sendObavestenjeResponse");
    private final static QName _SendResenje_QNAME = new QName("http://soap.email_service.ftn.uns.ac.rs/", "sendResenje");
    private final static QName _SendResenjeResponse_QNAME = new QName("http://soap.email_service.ftn.uns.ac.rs/", "sendResenjeResponse");
    private final static QName _SendZalba_QNAME = new QName("http://soap.email_service.ftn.uns.ac.rs/", "sendZalba");
    private final static QName _SendZalbaResponse_QNAME = new QName("http://soap.email_service.ftn.uns.ac.rs/", "sendZalbaResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.portal_poverenika.soap.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RejectNotification }
     * 
     */
    public RejectNotification createRejectNotification() {
        return new RejectNotification();
    }

    /**
     * Create an instance of {@link Notification }
     * 
     */
    public Notification createNotification() {
        return new Notification();
    }

    /**
     * Create an instance of {@link RejectZahtev }
     * 
     */
    public RejectZahtev createRejectZahtev() {
        return new RejectZahtev();
    }

    /**
     * Create an instance of {@link RejectZahtevResponse }
     * 
     */
    public RejectZahtevResponse createRejectZahtevResponse() {
        return new RejectZahtevResponse();
    }

    /**
     * Create an instance of {@link SendObavestenje }
     * 
     */
    public SendObavestenje createSendObavestenje() {
        return new SendObavestenje();
    }

    /**
     * Create an instance of {@link SendObavestenjeResponse }
     * 
     */
    public SendObavestenjeResponse createSendObavestenjeResponse() {
        return new SendObavestenjeResponse();
    }

    /**
     * Create an instance of {@link SendResenje }
     * 
     */
    public SendResenje createSendResenje() {
        return new SendResenje();
    }

    /**
     * Create an instance of {@link SendResenjeResponse }
     * 
     */
    public SendResenjeResponse createSendResenjeResponse() {
        return new SendResenjeResponse();
    }

    /**
     * Create an instance of {@link SendZalba }
     * 
     */
    public SendZalba createSendZalba() {
        return new SendZalba();
    }

    /**
     * Create an instance of {@link SendZalbaResponse }
     * 
     */
    public SendZalbaResponse createSendZalbaResponse() {
        return new SendZalbaResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RejectZahtev }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RejectZahtev }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.email_service.ftn.uns.ac.rs/", name = "rejectZahtev")
    public JAXBElement<RejectZahtev> createRejectZahtev(RejectZahtev value) {
        return new JAXBElement<RejectZahtev>(_RejectZahtev_QNAME, RejectZahtev.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RejectZahtevResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RejectZahtevResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.email_service.ftn.uns.ac.rs/", name = "rejectZahtevResponse")
    public JAXBElement<RejectZahtevResponse> createRejectZahtevResponse(RejectZahtevResponse value) {
        return new JAXBElement<RejectZahtevResponse>(_RejectZahtevResponse_QNAME, RejectZahtevResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendObavestenje }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SendObavestenje }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.email_service.ftn.uns.ac.rs/", name = "sendObavestenje")
    public JAXBElement<SendObavestenje> createSendObavestenje(SendObavestenje value) {
        return new JAXBElement<SendObavestenje>(_SendObavestenje_QNAME, SendObavestenje.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendObavestenjeResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SendObavestenjeResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.email_service.ftn.uns.ac.rs/", name = "sendObavestenjeResponse")
    public JAXBElement<SendObavestenjeResponse> createSendObavestenjeResponse(SendObavestenjeResponse value) {
        return new JAXBElement<SendObavestenjeResponse>(_SendObavestenjeResponse_QNAME, SendObavestenjeResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendResenje }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SendResenje }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.email_service.ftn.uns.ac.rs/", name = "sendResenje")
    public JAXBElement<SendResenje> createSendResenje(SendResenje value) {
        return new JAXBElement<SendResenje>(_SendResenje_QNAME, SendResenje.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendResenjeResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SendResenjeResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.email_service.ftn.uns.ac.rs/", name = "sendResenjeResponse")
    public JAXBElement<SendResenjeResponse> createSendResenjeResponse(SendResenjeResponse value) {
        return new JAXBElement<SendResenjeResponse>(_SendResenjeResponse_QNAME, SendResenjeResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendZalba }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SendZalba }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.email_service.ftn.uns.ac.rs/", name = "sendZalba")
    public JAXBElement<SendZalba> createSendZalba(SendZalba value) {
        return new JAXBElement<SendZalba>(_SendZalba_QNAME, SendZalba.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendZalbaResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SendZalbaResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.email_service.ftn.uns.ac.rs/", name = "sendZalbaResponse")
    public JAXBElement<SendZalbaResponse> createSendZalbaResponse(SendZalbaResponse value) {
        return new JAXBElement<SendZalbaResponse>(_SendZalbaResponse_QNAME, SendZalbaResponse.class, null, value);
    }

}
