//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.12 at 12:35:08 AM CET 
//


package obavestenje;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="informacije_o_obavestenju">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="id" type="{obavestenje}TId"/>
 *                   &lt;element name="broj_predmeta">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;pattern value="[0123456789\-/]+"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="organ_vlasti" type="{obavestenje}TPravno_Lice"/>
 *                   &lt;element name="podnosilac_zahteva" type="{obavestenje}TFIzicko_Lice"/>
 *                   &lt;element name="datum_obavestenja">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;pattern value="\d{2}\.\d{2}\.\d{4}\."/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="dostavljeno">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="imenovanom" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="arhivi" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="tekst_obavestenja">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="naslov" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="p" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="godina">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;length value="5"/>
 *                                   &lt;pattern value="\d{4}\."/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="trazena_informacija" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="datum_uvida">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;pattern value="\d{2}\.\d{2}\.\d{4}\."/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="vreme_uvida">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="sati" minOccurs="0">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;minLength value="2"/>
 *                                             &lt;maxLength value="5"/>
 *                                             &lt;pattern value="\d{2}:\d{2}"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                       &lt;element name="od" minOccurs="0">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;minLength value="2"/>
 *                                             &lt;maxLength value="5"/>
 *                                             &lt;pattern value="\d{2}:\d{2}"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                       &lt;element name="do" minOccurs="0">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;minLength value="2"/>
 *                                             &lt;maxLength value="5"/>
 *                                             &lt;pattern value="\d{2}:\d{2}"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="mesto_uvida">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="adresa" type="{obavestenje}TAdresa"/>
 *                                       &lt;element name="broj_kancelarije" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="troskovi" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "informacijeOObavestenju",
    "tekstObavestenja"
})
@XmlRootElement(name = "Obavestenje")
public class Obavestenje {

    @XmlElement(name = "informacije_o_obavestenju", required = true)
    protected Obavestenje.InformacijeOObavestenju informacijeOObavestenju;
    @XmlElement(name = "tekst_obavestenja", required = true)
    protected Obavestenje.TekstObavestenja tekstObavestenja;

    /**
     * Gets the value of the informacijeOObavestenju property.
     * 
     * @return
     *     possible object is
     *     {@link Obavestenje.InformacijeOObavestenju }
     *     
     */
    public Obavestenje.InformacijeOObavestenju getInformacijeOObavestenju() {
        return informacijeOObavestenju;
    }

    /**
     * Sets the value of the informacijeOObavestenju property.
     * 
     * @param value
     *     allowed object is
     *     {@link Obavestenje.InformacijeOObavestenju }
     *     
     */
    public void setInformacijeOObavestenju(Obavestenje.InformacijeOObavestenju value) {
        this.informacijeOObavestenju = value;
    }

    /**
     * Gets the value of the tekstObavestenja property.
     * 
     * @return
     *     possible object is
     *     {@link Obavestenje.TekstObavestenja }
     *     
     */
    public Obavestenje.TekstObavestenja getTekstObavestenja() {
        return tekstObavestenja;
    }

    /**
     * Sets the value of the tekstObavestenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link Obavestenje.TekstObavestenja }
     *     
     */
    public void setTekstObavestenja(Obavestenje.TekstObavestenja value) {
        this.tekstObavestenja = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="id" type="{obavestenje}TId"/>
     *         &lt;element name="broj_predmeta">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;pattern value="[0123456789\-/]+"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="organ_vlasti" type="{obavestenje}TPravno_Lice"/>
     *         &lt;element name="podnosilac_zahteva" type="{obavestenje}TFIzicko_Lice"/>
     *         &lt;element name="datum_obavestenja">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;pattern value="\d{2}\.\d{2}\.\d{4}\."/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="dostavljeno">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="imenovanom" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="arhivi" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "brojPredmeta",
        "organVlasti",
        "podnosilacZahteva",
        "datumObavestenja",
        "dostavljeno"
    })
    public static class InformacijeOObavestenju {

        @XmlElement(required = true)
        protected TId id;
        @XmlElement(name = "broj_predmeta", required = true)
        protected String brojPredmeta;
        @XmlElement(name = "organ_vlasti", required = true)
        protected TPravnoLice organVlasti;
        @XmlElement(name = "podnosilac_zahteva", required = true)
        protected TFIzickoLice podnosilacZahteva;
        @XmlElement(name = "datum_obavestenja", required = true)
        protected String datumObavestenja;
        @XmlElement(required = true)
        protected Obavestenje.InformacijeOObavestenju.Dostavljeno dostavljeno;

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link TId }
         *     
         */
        public TId getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link TId }
         *     
         */
        public void setId(TId value) {
            this.id = value;
        }

        /**
         * Gets the value of the brojPredmeta property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBrojPredmeta() {
            return brojPredmeta;
        }

        /**
         * Sets the value of the brojPredmeta property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBrojPredmeta(String value) {
            this.brojPredmeta = value;
        }

        /**
         * Gets the value of the organVlasti property.
         * 
         * @return
         *     possible object is
         *     {@link TPravnoLice }
         *     
         */
        public TPravnoLice getOrganVlasti() {
            return organVlasti;
        }

        /**
         * Sets the value of the organVlasti property.
         * 
         * @param value
         *     allowed object is
         *     {@link TPravnoLice }
         *     
         */
        public void setOrganVlasti(TPravnoLice value) {
            this.organVlasti = value;
        }

        /**
         * Gets the value of the podnosilacZahteva property.
         * 
         * @return
         *     possible object is
         *     {@link TFIzickoLice }
         *     
         */
        public TFIzickoLice getPodnosilacZahteva() {
            return podnosilacZahteva;
        }

        /**
         * Sets the value of the podnosilacZahteva property.
         * 
         * @param value
         *     allowed object is
         *     {@link TFIzickoLice }
         *     
         */
        public void setPodnosilacZahteva(TFIzickoLice value) {
            this.podnosilacZahteva = value;
        }

        /**
         * Gets the value of the datumObavestenja property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDatumObavestenja() {
            return datumObavestenja;
        }

        /**
         * Sets the value of the datumObavestenja property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDatumObavestenja(String value) {
            this.datumObavestenja = value;
        }

        /**
         * Gets the value of the dostavljeno property.
         * 
         * @return
         *     possible object is
         *     {@link Obavestenje.InformacijeOObavestenju.Dostavljeno }
         *     
         */
        public Obavestenje.InformacijeOObavestenju.Dostavljeno getDostavljeno() {
            return dostavljeno;
        }

        /**
         * Sets the value of the dostavljeno property.
         * 
         * @param value
         *     allowed object is
         *     {@link Obavestenje.InformacijeOObavestenju.Dostavljeno }
         *     
         */
        public void setDostavljeno(Obavestenje.InformacijeOObavestenju.Dostavljeno value) {
            this.dostavljeno = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="imenovanom" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="arhivi" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "imenovanom",
            "arhivi"
        })
        public static class Dostavljeno {

            @XmlElement(required = true)
            protected String imenovanom;
            @XmlElement(required = true)
            protected String arhivi;

            /**
             * Gets the value of the imenovanom property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getImenovanom() {
                return imenovanom;
            }

            /**
             * Sets the value of the imenovanom property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setImenovanom(String value) {
                this.imenovanom = value;
            }

            /**
             * Gets the value of the arhivi property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getArhivi() {
                return arhivi;
            }

            /**
             * Sets the value of the arhivi property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setArhivi(String value) {
                this.arhivi = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="naslov" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="p" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="godina">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;length value="5"/>
     *                         &lt;pattern value="\d{4}\."/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="trazena_informacija" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="datum_uvida">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;pattern value="\d{2}\.\d{2}\.\d{4}\."/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="vreme_uvida">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="sati" minOccurs="0">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;minLength value="2"/>
     *                                   &lt;maxLength value="5"/>
     *                                   &lt;pattern value="\d{2}:\d{2}"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element name="od" minOccurs="0">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;minLength value="2"/>
     *                                   &lt;maxLength value="5"/>
     *                                   &lt;pattern value="\d{2}:\d{2}"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element name="do" minOccurs="0">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;minLength value="2"/>
     *                                   &lt;maxLength value="5"/>
     *                                   &lt;pattern value="\d{2}:\d{2}"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="mesto_uvida">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="adresa" type="{obavestenje}TAdresa"/>
     *                             &lt;element name="broj_kancelarije" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="troskovi" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "naslov",
        "p"
    })
    public static class TekstObavestenja {

        @XmlElement(required = true)
        protected String naslov;
        @XmlElement(required = true)
        protected List<Obavestenje.TekstObavestenja.P> p;

        /**
         * Gets the value of the naslov property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNaslov() {
            return naslov;
        }

        /**
         * Sets the value of the naslov property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNaslov(String value) {
            this.naslov = value;
        }

        /**
         * Gets the value of the p property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the p property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getP().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Obavestenje.TekstObavestenja.P }
         * 
         * 
         */
        public List<Obavestenje.TekstObavestenja.P> getP() {
            if (p == null) {
                p = new ArrayList<Obavestenje.TekstObavestenja.P>();
            }
            return this.p;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="godina">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;length value="5"/>
         *               &lt;pattern value="\d{4}\."/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="trazena_informacija" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="datum_uvida">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;pattern value="\d{2}\.\d{2}\.\d{4}\."/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="vreme_uvida">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="sati" minOccurs="0">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;minLength value="2"/>
         *                         &lt;maxLength value="5"/>
         *                         &lt;pattern value="\d{2}:\d{2}"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element name="od" minOccurs="0">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;minLength value="2"/>
         *                         &lt;maxLength value="5"/>
         *                         &lt;pattern value="\d{2}:\d{2}"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element name="do" minOccurs="0">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;minLength value="2"/>
         *                         &lt;maxLength value="5"/>
         *                         &lt;pattern value="\d{2}:\d{2}"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="mesto_uvida">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="adresa" type="{obavestenje}TAdresa"/>
         *                   &lt;element name="broj_kancelarije" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="troskovi" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "content"
        })
        public static class P {

            @XmlElementRefs({
                @XmlElementRef(name = "vreme_uvida", namespace = "obavestenje", type = JAXBElement.class),
                @XmlElementRef(name = "troskovi", namespace = "obavestenje", type = JAXBElement.class),
                @XmlElementRef(name = "trazena_informacija", namespace = "obavestenje", type = JAXBElement.class),
                @XmlElementRef(name = "mesto_uvida", namespace = "obavestenje", type = JAXBElement.class),
                @XmlElementRef(name = "godina", namespace = "obavestenje", type = JAXBElement.class),
                @XmlElementRef(name = "datum_uvida", namespace = "obavestenje", type = JAXBElement.class)
            })
            @XmlMixed
            protected List<Serializable> content;

            /**
             * Gets the value of the content property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the content property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getContent().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link JAXBElement }{@code <}{@link Obavestenje.TekstObavestenja.P.VremeUvida }{@code >}
             * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link Obavestenje.TekstObavestenja.P.MestoUvida }{@code >}
             * {@link String }
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * 
             * 
             */
            public List<Serializable> getContent() {
                if (content == null) {
                    content = new ArrayList<Serializable>();
                }
                return this.content;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="adresa" type="{obavestenje}TAdresa"/>
             *         &lt;element name="broj_kancelarije" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "content"
            })
            public static class MestoUvida {

                @XmlElementRefs({
                    @XmlElementRef(name = "broj_kancelarije", namespace = "obavestenje", type = JAXBElement.class),
                    @XmlElementRef(name = "adresa", namespace = "obavestenje", type = JAXBElement.class)
                })
                @XmlMixed
                protected List<Serializable> content;

                /**
                 * Gets the value of the content property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the content property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getContent().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link String }
                 * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
                 * {@link JAXBElement }{@code <}{@link TAdresa }{@code >}
                 * 
                 * 
                 */
                public List<Serializable> getContent() {
                    if (content == null) {
                        content = new ArrayList<Serializable>();
                    }
                    return this.content;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="sati" minOccurs="0">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;minLength value="2"/>
             *               &lt;maxLength value="5"/>
             *               &lt;pattern value="\d{2}:\d{2}"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="od" minOccurs="0">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;minLength value="2"/>
             *               &lt;maxLength value="5"/>
             *               &lt;pattern value="\d{2}:\d{2}"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="do" minOccurs="0">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;minLength value="2"/>
             *               &lt;maxLength value="5"/>
             *               &lt;pattern value="\d{2}:\d{2}"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "content"
            })
            public static class VremeUvida {

                @XmlElementRefs({
                    @XmlElementRef(name = "do", namespace = "obavestenje", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "od", namespace = "obavestenje", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "sati", namespace = "obavestenje", type = JAXBElement.class, required = false)
                })
                @XmlMixed
                protected List<Serializable> content;

                /**
                 * Gets the value of the content property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the content property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getContent().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * {@link String }
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * 
                 * 
                 */
                public List<Serializable> getContent() {
                    if (content == null) {
                        content = new ArrayList<Serializable>();
                    }
                    return this.content;
                }

            }

        }

    }

}
