//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.12 at 12:35:08 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "obavestenje", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ftn.unc.as.rs.xml.poc.jaxb.model.obavestenje;
