//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.27 at 10:50:05 PM CET 
//


package rs.ac.uns.ftn.portal_organa_vlasti.model.types;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.portal_organa_vlasti.model.types package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _NewElement_QNAME = new QName("http://www.ftn.uns.ac.rs/types", "newElement");
    private final static QName _TMestoDatumDatum_QNAME = new QName("http://www.ftn.uns.ac.rs/types", "datum");
    private final static QName _TMestoDatumMesto_QNAME = new QName("http://www.ftn.uns.ac.rs/types", "mesto");
    private final static QName _TAdresaBroj_QNAME = new QName("http://www.ftn.uns.ac.rs/types", "broj");
    private final static QName _TAdresaUlica_QNAME = new QName("http://www.ftn.uns.ac.rs/types", "ulica");
    private final static QName _TLiceAdresa_QNAME = new QName("http://www.ftn.uns.ac.rs/types", "adresa");
    private final static QName _TTekstP_QNAME = new QName("http://www.ftn.uns.ac.rs/types", "p");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.portal_organa_vlasti.model.types
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TAdresa }
     * 
     */
    public TAdresa createTAdresa() {
        return new TAdresa();
    }

    /**
     * Create an instance of {@link TMestoDatum }
     * 
     */
    public TMestoDatum createTMestoDatum() {
        return new TMestoDatum();
    }

    /**
     * Create an instance of {@link TTekst }
     * 
     */
    public TTekst createTTekst() {
        return new TTekst();
    }

    /**
     * Create an instance of {@link TPravnoLice }
     * 
     */
    public TPravnoLice createTPravnoLice() {
        return new TPravnoLice();
    }

    /**
     * Create an instance of {@link TFIzickoLice }
     * 
     */
    public TFIzickoLice createTFIzickoLice() {
        return new TFIzickoLice();
    }

    /**
     * Create an instance of {@link TId }
     * 
     */
    public TId createTId() {
        return new TId();
    }

    /**
     * Create an instance of {@link TAdresa.Mesto }
     * 
     */
    public TAdresa.Mesto createTAdresaMesto() {
        return new TAdresa.Mesto();
    }

    /**
     * Create an instance of {@link TAdresa.Ulica }
     * 
     */
    public TAdresa.Ulica createTAdresaUlica() {
        return new TAdresa.Ulica();
    }

    /**
     * Create an instance of {@link TAdresa.Broj }
     * 
     */
    public TAdresa.Broj createTAdresaBroj() {
        return new TAdresa.Broj();
    }

    /**
     * Create an instance of {@link TMestoDatum.Mesto }
     * 
     */
    public TMestoDatum.Mesto createTMestoDatumMesto() {
        return new TMestoDatum.Mesto();
    }

    /**
     * Create an instance of {@link TMestoDatum.Datum }
     * 
     */
    public TMestoDatum.Datum createTMestoDatumDatum() {
        return new TMestoDatum.Datum();
    }

    /**
     * Create an instance of {@link TTekst.P }
     * 
     */
    public TTekst.P createTTekstP() {
        return new TTekst.P();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "newElement")
    public JAXBElement<String> createNewElement(String value) {
        return new JAXBElement<String>(_NewElement_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TMestoDatum.Datum }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "datum", scope = TMestoDatum.class)
    public JAXBElement<TMestoDatum.Datum> createTMestoDatumDatum(TMestoDatum.Datum value) {
        return new JAXBElement<TMestoDatum.Datum>(_TMestoDatumDatum_QNAME, TMestoDatum.Datum.class, TMestoDatum.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TMestoDatum.Mesto }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "mesto", scope = TMestoDatum.class)
    public JAXBElement<TMestoDatum.Mesto> createTMestoDatumMesto(TMestoDatum.Mesto value) {
        return new JAXBElement<TMestoDatum.Mesto>(_TMestoDatumMesto_QNAME, TMestoDatum.Mesto.class, TMestoDatum.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TAdresa.Broj }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "broj", scope = TAdresa.class)
    public JAXBElement<TAdresa.Broj> createTAdresaBroj(TAdresa.Broj value) {
        return new JAXBElement<TAdresa.Broj>(_TAdresaBroj_QNAME, TAdresa.Broj.class, TAdresa.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TAdresa.Ulica }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "ulica", scope = TAdresa.class)
    public JAXBElement<TAdresa.Ulica> createTAdresaUlica(TAdresa.Ulica value) {
        return new JAXBElement<TAdresa.Ulica>(_TAdresaUlica_QNAME, TAdresa.Ulica.class, TAdresa.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TAdresa.Mesto }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "mesto", scope = TAdresa.class)
    public JAXBElement<TAdresa.Mesto> createTAdresaMesto(TAdresa.Mesto value) {
        return new JAXBElement<TAdresa.Mesto>(_TMestoDatumMesto_QNAME, TAdresa.Mesto.class, TAdresa.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TAdresa }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "adresa", scope = TLice.class)
    public JAXBElement<TAdresa> createTLiceAdresa(TAdresa value) {
        return new JAXBElement<TAdresa>(_TLiceAdresa_QNAME, TAdresa.class, TLice.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTekst.P }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "p", scope = TTekst.class)
    public JAXBElement<TTekst.P> createTTekstP(TTekst.P value) {
        return new JAXBElement<TTekst.P>(_TTekstP_QNAME, TTekst.P.class, TTekst.class, value);
    }

}
