//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.06 at 12:37:18 PM CET 
//


package rs.ac.uns.ftn.portal_poverenika.soap.model.zahtev;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;
import java.util.HashMap;
import java.util.Map;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="organ_vlasti" type="{http://www.ftn.uns.ac.rs/types}TPravno_Lice"/&gt;
 *         &lt;element name="naslov_dokumenta" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="zakon" type="{http://www.ftn.uns.ac.rs/zahtev}TZakon"/&gt;
 *         &lt;element name="lista_zahteva" type="{http://www.ftn.uns.ac.rs/zahtev}TLista_zahteva"/&gt;
 *         &lt;element name="informacije" type="{http://www.ftn.uns.ac.rs/zahtev}TInformacije"/&gt;
 *         &lt;element name="mesto_i_datum" type="{http://www.ftn.uns.ac.rs/types}TMesto_Datum"/&gt;
 *         &lt;element name="podnosilac_zahteva" type="{http://www.ftn.uns.ac.rs/types}TFIzicko_Lice"/&gt;
 *         &lt;element name="lista_napomena" type="{http://www.ftn.uns.ac.rs/zahtev}TLista_napomena"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="userId" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="datum" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *       &lt;attribute name="about" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="status" type="{http://www.ftn.uns.ac.rs/zahtev}status" /&gt;
 *       &lt;anyAttribute processContents='skip' namespace='##other'/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "organVlasti",
    "naslovDokumenta",
    "zakon",
    "listaZahteva",
    "informacije",
    "mestoIDatum",
    "podnosilacZahteva",
    "listaNapomena"
})
@XmlRootElement(name = "dokument_zahtev")
public class DokumentZahtev {

    @XmlElement(name = "organ_vlasti", required = true)
    protected TPravnoLice organVlasti;
    @XmlElement(name = "naslov_dokumenta", required = true)
    protected String naslovDokumenta;
    @XmlElement(required = true)
    protected TZakon zakon;
    @XmlElement(name = "lista_zahteva", required = true)
    protected TListaZahteva listaZahteva;
    @XmlElement(required = true)
    protected TInformacije informacije;
    @XmlElement(name = "mesto_i_datum", required = true)
    protected TMestoDatum mestoIDatum;
    @XmlElement(name = "podnosilac_zahteva", required = true)
    protected TFIzickoLice podnosilacZahteva;
    @XmlElement(name = "lista_napomena", required = true)
    protected TListaNapomena listaNapomena;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "userId")
    protected String userId;
    @XmlAttribute(name = "datum")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datum;
    @XmlAttribute(name = "about")
    protected String about;
    @XmlAttribute(name = "status")
    protected Status status;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the organVlasti property.
     * 
     * @return
     *     possible object is
     *     {@link TPravnoLice }
     *     
     */
    public TPravnoLice getOrganVlasti() {
        return organVlasti;
    }

    /**
     * Sets the value of the organVlasti property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPravnoLice }
     *     
     */
    public void setOrganVlasti(TPravnoLice value) {
        this.organVlasti = value;
    }

    /**
     * Gets the value of the naslovDokumenta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNaslovDokumenta() {
        return naslovDokumenta;
    }

    /**
     * Sets the value of the naslovDokumenta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNaslovDokumenta(String value) {
        this.naslovDokumenta = value;
    }

    /**
     * Gets the value of the zakon property.
     * 
     * @return
     *     possible object is
     *     {@link TZakon }
     *     
     */
    public TZakon getZakon() {
        return zakon;
    }

    /**
     * Sets the value of the zakon property.
     * 
     * @param value
     *     allowed object is
     *     {@link TZakon }
     *     
     */
    public void setZakon(TZakon value) {
        this.zakon = value;
    }

    /**
     * Gets the value of the listaZahteva property.
     * 
     * @return
     *     possible object is
     *     {@link TListaZahteva }
     *     
     */
    public TListaZahteva getListaZahteva() {
        return listaZahteva;
    }

    /**
     * Sets the value of the listaZahteva property.
     * 
     * @param value
     *     allowed object is
     *     {@link TListaZahteva }
     *     
     */
    public void setListaZahteva(TListaZahteva value) {
        this.listaZahteva = value;
    }

    /**
     * Gets the value of the informacije property.
     * 
     * @return
     *     possible object is
     *     {@link TInformacije }
     *     
     */
    public TInformacije getInformacije() {
        return informacije;
    }

    /**
     * Sets the value of the informacije property.
     * 
     * @param value
     *     allowed object is
     *     {@link TInformacije }
     *     
     */
    public void setInformacije(TInformacije value) {
        this.informacije = value;
    }

    /**
     * Gets the value of the mestoIDatum property.
     * 
     * @return
     *     possible object is
     *     {@link TMestoDatum }
     *     
     */
    public TMestoDatum getMestoIDatum() {
        return mestoIDatum;
    }

    /**
     * Sets the value of the mestoIDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link TMestoDatum }
     *     
     */
    public void setMestoIDatum(TMestoDatum value) {
        this.mestoIDatum = value;
    }

    /**
     * Gets the value of the podnosilacZahteva property.
     * 
     * @return
     *     possible object is
     *     {@link TFIzickoLice }
     *     
     */
    public TFIzickoLice getPodnosilacZahteva() {
        return podnosilacZahteva;
    }

    /**
     * Sets the value of the podnosilacZahteva property.
     * 
     * @param value
     *     allowed object is
     *     {@link TFIzickoLice }
     *     
     */
    public void setPodnosilacZahteva(TFIzickoLice value) {
        this.podnosilacZahteva = value;
    }

    /**
     * Gets the value of the listaNapomena property.
     * 
     * @return
     *     possible object is
     *     {@link TListaNapomena }
     *     
     */
    public TListaNapomena getListaNapomena() {
        return listaNapomena;
    }

    /**
     * Sets the value of the listaNapomena property.
     * 
     * @param value
     *     allowed object is
     *     {@link TListaNapomena }
     *     
     */
    public void setListaNapomena(TListaNapomena value) {
        this.listaNapomena = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the userId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserId(String value) {
        this.userId = value;
    }

    /**
     * Gets the value of the datum property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatum() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatum(XMLGregorianCalendar value) {
        this.datum = value;
    }

    /**
     * Gets the value of the about property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbout() {
        return about;
    }

    /**
     * Sets the value of the about property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbout(String value) {
        this.about = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link Status }
     *     
     */
    public Status getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link Status }
     *     
     */
    public void setStatus(Status value) {
        this.status = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
