//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.06 at 12:37:18 PM CET 
//


package rs.ac.uns.ftn.portal_poverenika.soap.model.zahtev;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import java.math.BigInteger;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.portal_poverenika.soap.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetZahtevById_QNAME = new QName("http://zahtev.soap.portal_organa_vlasti.ftn.uns.ac.rs/", "getZahtevById");
    private final static QName _GetZahtevByIdResponse_QNAME = new QName("http://zahtev.soap.portal_organa_vlasti.ftn.uns.ac.rs/", "getZahtevByIdResponse");
    private final static QName _TTekstP_QNAME = new QName("http://www.ftn.uns.ac.rs/types", "p");
    private final static QName _TAdresaMesto_QNAME = new QName("http://www.ftn.uns.ac.rs/types", "mesto");
    private final static QName _TAdresaUlica_QNAME = new QName("http://www.ftn.uns.ac.rs/types", "ulica");
    private final static QName _TAdresaBroj_QNAME = new QName("http://www.ftn.uns.ac.rs/types", "broj");
    private final static QName _TNacinDrugiNacin_QNAME = new QName("http://www.ftn.uns.ac.rs/zahtev", "drugi_nacin");
    private final static QName _TZahtevNapomena_QNAME = new QName("http://www.ftn.uns.ac.rs/zahtev", "napomena");
    private final static QName _TZahtevListaNacina_QNAME = new QName("http://www.ftn.uns.ac.rs/zahtev", "lista_nacina");
    private final static QName _TFIzickoLiceIme_QNAME = new QName("http://www.ftn.uns.ac.rs/types", "ime");
    private final static QName _TFIzickoLicePrezime_QNAME = new QName("http://www.ftn.uns.ac.rs/types", "prezime");
    private final static QName _TFIzickoLiceAdresa_QNAME = new QName("http://www.ftn.uns.ac.rs/types", "adresa");
    private final static QName _TFIzickoLiceDrugiPodaciZaKontakt_QNAME = new QName("http://www.ftn.uns.ac.rs/types", "drugi_podaci_za_kontakt");
    private final static QName _TFIzickoLicePotpis_QNAME = new QName("http://www.ftn.uns.ac.rs/types", "potpis");
    private final static QName _TMestoDatumDatum_QNAME = new QName("http://www.ftn.uns.ac.rs/types", "datum");
    private final static QName _TInformacijeSadrzajInformacija_QNAME = new QName("http://www.ftn.uns.ac.rs/zahtev", "sadrzaj_informacija");
    private final static QName _TPravnoLiceNazivOrgana_QNAME = new QName("http://www.ftn.uns.ac.rs/types", "naziv_organa");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.portal_poverenika.soap.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetZahtevByIdResponse }
     * 
     */
    public GetZahtevByIdResponse createGetZahtevByIdResponse() {
        return new GetZahtevByIdResponse();
    }

    /**
     * Create an instance of {@link GetZahtevById }
     * 
     */
    public GetZahtevById createGetZahtevById() {
        return new GetZahtevById();
    }

    /**
     * Create an instance of {@link DokumentZahtev }
     * 
     */
    public DokumentZahtev createDokumentZahtev() {
        return new DokumentZahtev();
    }

    /**
     * Create an instance of {@link TPravnoLice }
     * 
     */
    public TPravnoLice createTPravnoLice() {
        return new TPravnoLice();
    }

    /**
     * Create an instance of {@link TZakon }
     * 
     */
    public TZakon createTZakon() {
        return new TZakon();
    }

    /**
     * Create an instance of {@link TListaZahteva }
     * 
     */
    public TListaZahteva createTListaZahteva() {
        return new TListaZahteva();
    }

    /**
     * Create an instance of {@link TInformacije }
     * 
     */
    public TInformacije createTInformacije() {
        return new TInformacije();
    }

    /**
     * Create an instance of {@link TMestoDatum }
     * 
     */
    public TMestoDatum createTMestoDatum() {
        return new TMestoDatum();
    }

    /**
     * Create an instance of {@link TFIzickoLice }
     * 
     */
    public TFIzickoLice createTFIzickoLice() {
        return new TFIzickoLice();
    }

    /**
     * Create an instance of {@link TListaNapomena }
     * 
     */
    public TListaNapomena createTListaNapomena() {
        return new TListaNapomena();
    }

    /**
     * Create an instance of {@link TZahtev }
     * 
     */
    public TZahtev createTZahtev() {
        return new TZahtev();
    }

    /**
     * Create an instance of {@link TNapomena }
     * 
     */
    public TNapomena createTNapomena() {
        return new TNapomena();
    }

    /**
     * Create an instance of {@link TDrugiNacin }
     * 
     */
    public TDrugiNacin createTDrugiNacin() {
        return new TDrugiNacin();
    }

    /**
     * Create an instance of {@link TListaNacina }
     * 
     */
    public TListaNacina createTListaNacina() {
        return new TListaNacina();
    }

    /**
     * Create an instance of {@link TNacin }
     * 
     */
    public TNacin createTNacin() {
        return new TNacin();
    }

    /**
     * Create an instance of {@link TAdresa }
     * 
     */
    public TAdresa createTAdresa() {
        return new TAdresa();
    }

    /**
     * Create an instance of {@link TTekst }
     * 
     */
    public TTekst createTTekst() {
        return new TTekst();
    }

    /**
     * Create an instance of {@link GetZahtevByIdResponse.Return }
     * 
     */
    public GetZahtevByIdResponse.Return createGetZahtevByIdResponseReturn() {
        return new GetZahtevByIdResponse.Return();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetZahtevById }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetZahtevById }{@code >}
     */
    @XmlElementDecl(namespace = "http://zahtev.soap.portal_organa_vlasti.ftn.uns.ac.rs/", name = "getZahtevById")
    public JAXBElement<GetZahtevById> createGetZahtevById(GetZahtevById value) {
        return new JAXBElement<GetZahtevById>(_GetZahtevById_QNAME, GetZahtevById.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetZahtevByIdResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetZahtevByIdResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://zahtev.soap.portal_organa_vlasti.ftn.uns.ac.rs/", name = "getZahtevByIdResponse")
    public JAXBElement<GetZahtevByIdResponse> createGetZahtevByIdResponse(GetZahtevByIdResponse value) {
        return new JAXBElement<GetZahtevByIdResponse>(_GetZahtevByIdResponse_QNAME, GetZahtevByIdResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "p", scope = TTekst.class)
    public JAXBElement<String> createTTekstP(String value) {
        return new JAXBElement<String>(_TTekstP_QNAME, String.class, TTekst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "mesto", scope = TAdresa.class)
    public JAXBElement<String> createTAdresaMesto(String value) {
        return new JAXBElement<String>(_TAdresaMesto_QNAME, String.class, TAdresa.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "ulica", scope = TAdresa.class)
    public JAXBElement<String> createTAdresaUlica(String value) {
        return new JAXBElement<String>(_TAdresaUlica_QNAME, String.class, TAdresa.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "broj", scope = TAdresa.class)
    public JAXBElement<BigInteger> createTAdresaBroj(BigInteger value) {
        return new JAXBElement<BigInteger>(_TAdresaBroj_QNAME, BigInteger.class, TAdresa.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TDrugiNacin }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TDrugiNacin }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zahtev", name = "drugi_nacin", scope = TNacin.class)
    public JAXBElement<TDrugiNacin> createTNacinDrugiNacin(TDrugiNacin value) {
        return new JAXBElement<TDrugiNacin>(_TNacinDrugiNacin_QNAME, TDrugiNacin.class, TNacin.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TNapomena }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TNapomena }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zahtev", name = "napomena", scope = TZahtev.class)
    public JAXBElement<TNapomena> createTZahtevNapomena(TNapomena value) {
        return new JAXBElement<TNapomena>(_TZahtevNapomena_QNAME, TNapomena.class, TZahtev.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TListaNacina }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TListaNacina }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zahtev", name = "lista_nacina", scope = TZahtev.class)
    public JAXBElement<TListaNacina> createTZahtevListaNacina(TListaNacina value) {
        return new JAXBElement<TListaNacina>(_TZahtevListaNacina_QNAME, TListaNacina.class, TZahtev.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "ime", scope = TFIzickoLice.class)
    public JAXBElement<String> createTFIzickoLiceIme(String value) {
        return new JAXBElement<String>(_TFIzickoLiceIme_QNAME, String.class, TFIzickoLice.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "prezime", scope = TFIzickoLice.class)
    public JAXBElement<String> createTFIzickoLicePrezime(String value) {
        return new JAXBElement<String>(_TFIzickoLicePrezime_QNAME, String.class, TFIzickoLice.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TAdresa }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TAdresa }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "adresa", scope = TFIzickoLice.class)
    public JAXBElement<TAdresa> createTFIzickoLiceAdresa(TAdresa value) {
        return new JAXBElement<TAdresa>(_TFIzickoLiceAdresa_QNAME, TAdresa.class, TFIzickoLice.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "drugi_podaci_za_kontakt", scope = TFIzickoLice.class)
    public JAXBElement<String> createTFIzickoLiceDrugiPodaciZaKontakt(String value) {
        return new JAXBElement<String>(_TFIzickoLiceDrugiPodaciZaKontakt_QNAME, String.class, TFIzickoLice.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "potpis", scope = TFIzickoLice.class)
    public JAXBElement<String> createTFIzickoLicePotpis(String value) {
        return new JAXBElement<String>(_TFIzickoLicePotpis_QNAME, String.class, TFIzickoLice.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "mesto", scope = TMestoDatum.class)
    public JAXBElement<String> createTMestoDatumMesto(String value) {
        return new JAXBElement<String>(_TAdresaMesto_QNAME, String.class, TMestoDatum.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "datum", scope = TMestoDatum.class)
    public JAXBElement<Object> createTMestoDatumDatum(Object value) {
        return new JAXBElement<Object>(_TMestoDatumDatum_QNAME, Object.class, TMestoDatum.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zahtev", name = "sadrzaj_informacija", scope = TInformacije.class)
    public JAXBElement<String> createTInformacijeSadrzajInformacija(String value) {
        return new JAXBElement<String>(_TInformacijeSadrzajInformacija_QNAME, String.class, TInformacije.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TNapomena }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TNapomena }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zahtev", name = "napomena", scope = TZakon.class)
    public JAXBElement<TNapomena> createTZakonNapomena(TNapomena value) {
        return new JAXBElement<TNapomena>(_TZahtevNapomena_QNAME, TNapomena.class, TZakon.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "naziv_organa", scope = TPravnoLice.class)
    public JAXBElement<String> createTPravnoLiceNazivOrgana(String value) {
        return new JAXBElement<String>(_TPravnoLiceNazivOrgana_QNAME, String.class, TPravnoLice.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TAdresa }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TAdresa }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "adresa", scope = TPravnoLice.class)
    public JAXBElement<TAdresa> createTPravnoLiceAdresa(TAdresa value) {
        return new JAXBElement<TAdresa>(_TFIzickoLiceAdresa_QNAME, TAdresa.class, TPravnoLice.class, value);
    }

}
