//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.08 at 12:00:48 AM CET 
//


package obavestenje;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the obavestenje package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: obavestenje
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Obavestenje }
     * 
     */
    public Obavestenje createObavestenje() {
        return new Obavestenje();
    }

    /**
     * Create an instance of {@link Obavestenje.TekstObavestenja }
     * 
     */
    public Obavestenje.TekstObavestenja createObavestenjeTekstObavestenja() {
        return new Obavestenje.TekstObavestenja();
    }

    /**
     * Create an instance of {@link Obavestenje.TekstObavestenja.UvidUInformacije }
     * 
     */
    public Obavestenje.TekstObavestenja.UvidUInformacije createObavestenjeTekstObavestenjaUvidUInformacije() {
        return new Obavestenje.TekstObavestenja.UvidUInformacije();
    }

    /**
     * Create an instance of {@link Obavestenje.TekstObavestenja.UvidUInformacije.VremeUvida }
     * 
     */
    public Obavestenje.TekstObavestenja.UvidUInformacije.VremeUvida createObavestenjeTekstObavestenjaUvidUInformacijeVremeUvida() {
        return new Obavestenje.TekstObavestenja.UvidUInformacije.VremeUvida();
    }

    /**
     * Create an instance of {@link Obavestenje.InformacijeOObavestenju }
     * 
     */
    public Obavestenje.InformacijeOObavestenju createObavestenjeInformacijeOObavestenju() {
        return new Obavestenje.InformacijeOObavestenju();
    }

    /**
     * Create an instance of {@link Adresa }
     * 
     */
    public Adresa createAdresa() {
        return new Adresa();
    }

    /**
     * Create an instance of {@link TAdresa }
     * 
     */
    public TAdresa createTAdresa() {
        return new TAdresa();
    }

    /**
     * Create an instance of {@link TPravnoLice }
     * 
     */
    public TPravnoLice createTPravnoLice() {
        return new TPravnoLice();
    }

    /**
     * Create an instance of {@link TFizickoLice }
     * 
     */
    public TFizickoLice createTFizickoLice() {
        return new TFizickoLice();
    }

    /**
     * Create an instance of {@link Obavestenje.TekstObavestenja.ZahtevInformacija }
     * 
     */
    public Obavestenje.TekstObavestenja.ZahtevInformacija createObavestenjeTekstObavestenjaZahtevInformacija() {
        return new Obavestenje.TekstObavestenja.ZahtevInformacija();
    }

    /**
     * Create an instance of {@link Obavestenje.TekstObavestenja.UvidUInformacije.MestoUvida }
     * 
     */
    public Obavestenje.TekstObavestenja.UvidUInformacije.MestoUvida createObavestenjeTekstObavestenjaUvidUInformacijeMestoUvida() {
        return new Obavestenje.TekstObavestenja.UvidUInformacije.MestoUvida();
    }

    /**
     * Create an instance of {@link Obavestenje.TekstObavestenja.UvidUInformacije.VremeUvida.IntervalVremena }
     * 
     */
    public Obavestenje.TekstObavestenja.UvidUInformacije.VremeUvida.IntervalVremena createObavestenjeTekstObavestenjaUvidUInformacijeVremeUvidaIntervalVremena() {
        return new Obavestenje.TekstObavestenja.UvidUInformacije.VremeUvida.IntervalVremena();
    }

    /**
     * Create an instance of {@link Obavestenje.InformacijeOObavestenju.Dostavljeno }
     * 
     */
    public Obavestenje.InformacijeOObavestenju.Dostavljeno createObavestenjeInformacijeOObavestenjuDostavljeno() {
        return new Obavestenje.InformacijeOObavestenju.Dostavljeno();
    }

}
