//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.06 at 02:26:21 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(
        namespace = "http://www.ftn.uns.ac.rs/zalba_protiv_odluke",
        elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
        location = "http://www.ftn.uns.ac.rs/zalba_protiv_odluke ../xsd/zalba_protiv_odluke.xsd",
        xmlns = {@XmlNs(prefix = "zpo", namespaceURI = "http://www.ftn.uns.ac.rs/zalba_protiv_odluke"),
                @XmlNs(prefix = "types", namespaceURI = "http://www.ftn.uns.ac.rs/types"),
                @XmlNs(prefix = "pred", namespaceURI = "http://examples/predicate/"),
                @XmlNs(prefix = "xsi", namespaceURI = "http://www.w3.org/2001/XMLSchema-instance")})package rs.ac.uns.ftn.portal_poverenika.model.zalba_protiv_odluke;

import javax.xml.bind.annotation.XmlNs;