//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.12 at 12:44:15 AM CET 
//


package zalba_cutanje;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the zalba_cutanje package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TAdresaMesto_QNAME = new QName("zalba_cutanje", "mesto");
    private final static QName _TAdresaUlica_QNAME = new QName("zalba_cutanje", "ulica");
    private final static QName _TAdresaBroj_QNAME = new QName("zalba_cutanje", "broj");
    private final static QName _PodaciOZalbiCutanjaDetaljiZalbePodaciOZalbi_QNAME = new QName("zalba_cutanje", "podaci_o_zalbi");
    private final static QName _PodaciOZalbiCutanjaDetaljiZalbeDatum_QNAME = new QName("zalba_cutanje", "datum");
    private final static QName _PodaciOZalbiCutanjaInformacijeOZalbiNaslov_QNAME = new QName("zalba_cutanje", "naslov");
    private final static QName _PodaciOZalbiCutanjaInformacijeOZalbiNazivOrgana_QNAME = new QName("zalba_cutanje", "naziv_organa");
    private final static QName _PodaciOZalbiCutanjaInformacijeOZalbiZakon_QNAME = new QName("zalba_cutanje", "zakon");
    private final static QName _TLiceAdresa_QNAME = new QName("zalba_cutanje", "Adresa");
    private final static QName _PodaciOZalbiCutanjaMestoIDatum_QNAME = new QName("zalba_cutanje", "mesto_i_datum");
    private final static QName _PodaciOZalbiCutanjaPodnosilacZalbe_QNAME = new QName("zalba_cutanje", "podnosilac_zalbe");
    private final static QName _PodaciOZalbiCutanjaId_QNAME = new QName("zalba_cutanje", "id");
    private final static QName _PodaciOZalbiCutanjaPredlogResenja_QNAME = new QName("zalba_cutanje", "predlog_resenja");
    private final static QName _PodaciOZalbiCutanjaVrstaZalbe_QNAME = new QName("zalba_cutanje", "vrsta_zalbe");
    private final static QName _PodaciOZalbiCutanjaInformacijeOZalbi_QNAME = new QName("zalba_cutanje", "informacije_o_zalbi");
    private final static QName _PodaciOZalbiCutanjaDetaljiZalbe_QNAME = new QName("zalba_cutanje", "detalji_zalbe");
    private final static QName _PodaciOZalbiCutanjaPrimaocZalbe_QNAME = new QName("zalba_cutanje", "primaoc_zalbe");
    private final static QName _PodaciOZalbiCutanjaRazlogZalbe_QNAME = new QName("zalba_cutanje", "razlog_zalbe");
    private final static QName _PodaciOZalbiCutanjaNapomena_QNAME = new QName("zalba_cutanje", "napomena");
    private final static QName _TTekstP_QNAME = new QName("zalba_cutanje", "p");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: zalba_cutanje
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PodaciOZalbiCutanja }
     * 
     */
    public PodaciOZalbiCutanja createPodaciOZalbiCutanja() {
        return new PodaciOZalbiCutanja();
    }

    /**
     * Create an instance of {@link TTekst }
     * 
     */
    public TTekst createTTekst() {
        return new TTekst();
    }

    /**
     * Create an instance of {@link TId }
     * 
     */
    public TId createTId() {
        return new TId();
    }

    /**
     * Create an instance of {@link TPravnoLice }
     * 
     */
    public TPravnoLice createTPravnoLice() {
        return new TPravnoLice();
    }

    /**
     * Create an instance of {@link PodaciOZalbiCutanja.InformacijeOZalbi }
     * 
     */
    public PodaciOZalbiCutanja.InformacijeOZalbi createPodaciOZalbiCutanjaInformacijeOZalbi() {
        return new PodaciOZalbiCutanja.InformacijeOZalbi();
    }

    /**
     * Create an instance of {@link PodaciOZalbiCutanja.DetaljiZalbe }
     * 
     */
    public PodaciOZalbiCutanja.DetaljiZalbe createPodaciOZalbiCutanjaDetaljiZalbe() {
        return new PodaciOZalbiCutanja.DetaljiZalbe();
    }

    /**
     * Create an instance of {@link PodaciOZalbiCutanja.PodnosilacZalbe }
     * 
     */
    public PodaciOZalbiCutanja.PodnosilacZalbe createPodaciOZalbiCutanjaPodnosilacZalbe() {
        return new PodaciOZalbiCutanja.PodnosilacZalbe();
    }

    /**
     * Create an instance of {@link TMestoDatum }
     * 
     */
    public TMestoDatum createTMestoDatum() {
        return new TMestoDatum();
    }

    /**
     * Create an instance of {@link TAdresa }
     * 
     */
    public TAdresa createTAdresa() {
        return new TAdresa();
    }

    /**
     * Create an instance of {@link TFIzickoLice }
     * 
     */
    public TFIzickoLice createTFIzickoLice() {
        return new TFIzickoLice();
    }

    /**
     * Create an instance of {@link TTekst.P }
     * 
     */
    public TTekst.P createTTekstP() {
        return new TTekst.P();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "zalba_cutanje", name = "mesto", scope = TAdresa.class)
    public JAXBElement<String> createTAdresaMesto(String value) {
        return new JAXBElement<String>(_TAdresaMesto_QNAME, String.class, TAdresa.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "zalba_cutanje", name = "ulica", scope = TAdresa.class)
    public JAXBElement<String> createTAdresaUlica(String value) {
        return new JAXBElement<String>(_TAdresaUlica_QNAME, String.class, TAdresa.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "zalba_cutanje", name = "broj", scope = TAdresa.class)
    public JAXBElement<BigInteger> createTAdresaBroj(BigInteger value) {
        return new JAXBElement<BigInteger>(_TAdresaBroj_QNAME, BigInteger.class, TAdresa.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "zalba_cutanje", name = "podaci_o_zalbi", scope = PodaciOZalbiCutanja.DetaljiZalbe.class)
    public JAXBElement<String> createPodaciOZalbiCutanjaDetaljiZalbePodaciOZalbi(String value) {
        return new JAXBElement<String>(_PodaciOZalbiCutanjaDetaljiZalbePodaciOZalbi_QNAME, String.class, PodaciOZalbiCutanja.DetaljiZalbe.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "zalba_cutanje", name = "datum", scope = PodaciOZalbiCutanja.DetaljiZalbe.class)
    public JAXBElement<String> createPodaciOZalbiCutanjaDetaljiZalbeDatum(String value) {
        return new JAXBElement<String>(_PodaciOZalbiCutanjaDetaljiZalbeDatum_QNAME, String.class, PodaciOZalbiCutanja.DetaljiZalbe.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "zalba_cutanje", name = "naslov", scope = PodaciOZalbiCutanja.InformacijeOZalbi.class)
    public JAXBElement<String> createPodaciOZalbiCutanjaInformacijeOZalbiNaslov(String value) {
        return new JAXBElement<String>(_PodaciOZalbiCutanjaInformacijeOZalbiNaslov_QNAME, String.class, PodaciOZalbiCutanja.InformacijeOZalbi.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "zalba_cutanje", name = "naziv_organa", scope = PodaciOZalbiCutanja.InformacijeOZalbi.class)
    public JAXBElement<String> createPodaciOZalbiCutanjaInformacijeOZalbiNazivOrgana(String value) {
        return new JAXBElement<String>(_PodaciOZalbiCutanjaInformacijeOZalbiNazivOrgana_QNAME, String.class, PodaciOZalbiCutanja.InformacijeOZalbi.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "zalba_cutanje", name = "zakon", scope = PodaciOZalbiCutanja.InformacijeOZalbi.class)
    public JAXBElement<String> createPodaciOZalbiCutanjaInformacijeOZalbiZakon(String value) {
        return new JAXBElement<String>(_PodaciOZalbiCutanjaInformacijeOZalbiZakon_QNAME, String.class, PodaciOZalbiCutanja.InformacijeOZalbi.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "zalba_cutanje", name = "mesto", scope = TMestoDatum.class)
    public JAXBElement<String> createTMestoDatumMesto(String value) {
        return new JAXBElement<String>(_TAdresaMesto_QNAME, String.class, TMestoDatum.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "zalba_cutanje", name = "datum", scope = TMestoDatum.class)
    public JAXBElement<String> createTMestoDatumDatum(String value) {
        return new JAXBElement<String>(_PodaciOZalbiCutanjaDetaljiZalbeDatum_QNAME, String.class, TMestoDatum.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TAdresa }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "zalba_cutanje", name = "Adresa", scope = TLice.class)
    public JAXBElement<TAdresa> createTLiceAdresa(TAdresa value) {
        return new JAXBElement<TAdresa>(_TLiceAdresa_QNAME, TAdresa.class, TLice.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TMestoDatum }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "zalba_cutanje", name = "mesto_i_datum", scope = PodaciOZalbiCutanja.class)
    public JAXBElement<TMestoDatum> createPodaciOZalbiCutanjaMestoIDatum(TMestoDatum value) {
        return new JAXBElement<TMestoDatum>(_PodaciOZalbiCutanjaMestoIDatum_QNAME, TMestoDatum.class, PodaciOZalbiCutanja.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PodaciOZalbiCutanja.PodnosilacZalbe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "zalba_cutanje", name = "podnosilac_zalbe", scope = PodaciOZalbiCutanja.class)
    public JAXBElement<PodaciOZalbiCutanja.PodnosilacZalbe> createPodaciOZalbiCutanjaPodnosilacZalbe(PodaciOZalbiCutanja.PodnosilacZalbe value) {
        return new JAXBElement<PodaciOZalbiCutanja.PodnosilacZalbe>(_PodaciOZalbiCutanjaPodnosilacZalbe_QNAME, PodaciOZalbiCutanja.PodnosilacZalbe.class, PodaciOZalbiCutanja.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TId }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "zalba_cutanje", name = "id", scope = PodaciOZalbiCutanja.class)
    public JAXBElement<TId> createPodaciOZalbiCutanjaId(TId value) {
        return new JAXBElement<TId>(_PodaciOZalbiCutanjaId_QNAME, TId.class, PodaciOZalbiCutanja.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "zalba_cutanje", name = "predlog_resenja", scope = PodaciOZalbiCutanja.class)
    public JAXBElement<String> createPodaciOZalbiCutanjaPredlogResenja(String value) {
        return new JAXBElement<String>(_PodaciOZalbiCutanjaPredlogResenja_QNAME, String.class, PodaciOZalbiCutanja.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "zalba_cutanje", name = "vrsta_zalbe", scope = PodaciOZalbiCutanja.class)
    public JAXBElement<String> createPodaciOZalbiCutanjaVrstaZalbe(String value) {
        return new JAXBElement<String>(_PodaciOZalbiCutanjaVrstaZalbe_QNAME, String.class, PodaciOZalbiCutanja.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PodaciOZalbiCutanja.InformacijeOZalbi }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "zalba_cutanje", name = "informacije_o_zalbi", scope = PodaciOZalbiCutanja.class)
    public JAXBElement<PodaciOZalbiCutanja.InformacijeOZalbi> createPodaciOZalbiCutanjaInformacijeOZalbi(PodaciOZalbiCutanja.InformacijeOZalbi value) {
        return new JAXBElement<PodaciOZalbiCutanja.InformacijeOZalbi>(_PodaciOZalbiCutanjaInformacijeOZalbi_QNAME, PodaciOZalbiCutanja.InformacijeOZalbi.class, PodaciOZalbiCutanja.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PodaciOZalbiCutanja.DetaljiZalbe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "zalba_cutanje", name = "detalji_zalbe", scope = PodaciOZalbiCutanja.class)
    public JAXBElement<PodaciOZalbiCutanja.DetaljiZalbe> createPodaciOZalbiCutanjaDetaljiZalbe(PodaciOZalbiCutanja.DetaljiZalbe value) {
        return new JAXBElement<PodaciOZalbiCutanja.DetaljiZalbe>(_PodaciOZalbiCutanjaDetaljiZalbe_QNAME, PodaciOZalbiCutanja.DetaljiZalbe.class, PodaciOZalbiCutanja.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TPravnoLice }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "zalba_cutanje", name = "primaoc_zalbe", scope = PodaciOZalbiCutanja.class)
    public JAXBElement<TPravnoLice> createPodaciOZalbiCutanjaPrimaocZalbe(TPravnoLice value) {
        return new JAXBElement<TPravnoLice>(_PodaciOZalbiCutanjaPrimaocZalbe_QNAME, TPravnoLice.class, PodaciOZalbiCutanja.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "zalba_cutanje", name = "razlog_zalbe", scope = PodaciOZalbiCutanja.class)
    public JAXBElement<String> createPodaciOZalbiCutanjaRazlogZalbe(String value) {
        return new JAXBElement<String>(_PodaciOZalbiCutanjaRazlogZalbe_QNAME, String.class, PodaciOZalbiCutanja.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "zalba_cutanje", name = "napomena", scope = PodaciOZalbiCutanja.class)
    public JAXBElement<String> createPodaciOZalbiCutanjaNapomena(String value) {
        return new JAXBElement<String>(_PodaciOZalbiCutanjaNapomena_QNAME, String.class, PodaciOZalbiCutanja.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTekst.P }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "zalba_cutanje", name = "p", scope = TTekst.class)
    public JAXBElement<TTekst.P> createTTekstP(TTekst.P value) {
        return new JAXBElement<TTekst.P>(_TTekstP_QNAME, TTekst.P.class, TTekst.class, value);
    }

}
