//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.25 at 10:45:16 PM CET 
//


package ftn.unc.as.rs.xml.poc.jaxb.model.zalbaProtivCutanja;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ftn.unc.as.rs.xml.poc.jaxb.model.zalbaProtivCutanja package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ZalbaProtivCutanjaInformacijeOZalbiNaslov_QNAME = new QName("zalba_protiv_cutanja", "naslov");
    private final static QName _ZalbaProtivCutanjaInformacijeOZalbiNazivOrgana_QNAME = new QName("zalba_protiv_cutanja", "naziv_organa");
    private final static QName _ZalbaProtivCutanjaInformacijeOZalbiZakon_QNAME = new QName("zalba_protiv_cutanja", "zakon");
    private final static QName _TLiceAdresa_QNAME = new QName("zalba_protiv_cutanja", "Adresa");
    private final static QName _TTekstP_QNAME = new QName("zalba_protiv_cutanja", "p");
    private final static QName _TMestoDatumDatum_QNAME = new QName("zalba_protiv_cutanja", "datum");
    private final static QName _TMestoDatumMesto_QNAME = new QName("zalba_protiv_cutanja", "mesto");
    private final static QName _ZalbaProtivCutanjaInformacijeOZalbi_QNAME = new QName("zalba_protiv_cutanja", "informacije_o_zalbi");
    private final static QName _ZalbaProtivCutanjaDetaljiZalbe_QNAME = new QName("zalba_protiv_cutanja", "detalji_zalbe");
    private final static QName _ZalbaProtivCutanjaPrimaocZalbe_QNAME = new QName("zalba_protiv_cutanja", "primaoc_zalbe");
    private final static QName _ZalbaProtivCutanjaRazlogZalbe_QNAME = new QName("zalba_protiv_cutanja", "razlog_zalbe");
    private final static QName _ZalbaProtivCutanjaNapomena_QNAME = new QName("zalba_protiv_cutanja", "napomena");
    private final static QName _ZalbaProtivCutanjaMestoIDatum_QNAME = new QName("zalba_protiv_cutanja", "mesto_i_datum");
    private final static QName _ZalbaProtivCutanjaPodnosilacZalbe_QNAME = new QName("zalba_protiv_cutanja", "podnosilac_zalbe");
    private final static QName _ZalbaProtivCutanjaId_QNAME = new QName("zalba_protiv_cutanja", "id");
    private final static QName _ZalbaProtivCutanjaPredlogResenja_QNAME = new QName("zalba_protiv_cutanja", "predlog_resenja");
    private final static QName _ZalbaProtivCutanjaVrstaZalbe_QNAME = new QName("zalba_protiv_cutanja", "vrsta_zalbe");
    private final static QName _TAdresaUlica_QNAME = new QName("zalba_protiv_cutanja", "ulica");
    private final static QName _TAdresaBroj_QNAME = new QName("zalba_protiv_cutanja", "broj");
    private final static QName _ZalbaProtivCutanjaDetaljiZalbePodaciOZalbi_QNAME = new QName("zalba_protiv_cutanja", "podaci_o_zalbi");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ftn.unc.as.rs.xml.poc.jaxb.model.zalbaProtivCutanja
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZalbaProtivCutanja }
     * 
     */
    public ZalbaProtivCutanja createZalbaProtivCutanja() {
        return new ZalbaProtivCutanja();
    }

    /**
     * Create an instance of {@link TAdresa }
     * 
     */
    public TAdresa createTAdresa() {
        return new TAdresa();
    }

    /**
     * Create an instance of {@link TTekst }
     * 
     */
    public TTekst createTTekst() {
        return new TTekst();
    }

    /**
     * Create an instance of {@link ZalbaProtivCutanja.DetaljiZalbe }
     * 
     */
    public ZalbaProtivCutanja.DetaljiZalbe createZalbaProtivCutanjaDetaljiZalbe() {
        return new ZalbaProtivCutanja.DetaljiZalbe();
    }

    /**
     * Create an instance of {@link ZalbaProtivCutanja.InformacijeOZalbi }
     * 
     */
    public ZalbaProtivCutanja.InformacijeOZalbi createZalbaProtivCutanjaInformacijeOZalbi() {
        return new ZalbaProtivCutanja.InformacijeOZalbi();
    }

    /**
     * Create an instance of {@link TId }
     * 
     */
    public TId createTId() {
        return new TId();
    }

    /**
     * Create an instance of {@link TPravnoLice }
     * 
     */
    public TPravnoLice createTPravnoLice() {
        return new TPravnoLice();
    }

    /**
     * Create an instance of {@link ZalbaProtivCutanja.PodnosilacZalbe }
     * 
     */
    public ZalbaProtivCutanja.PodnosilacZalbe createZalbaProtivCutanjaPodnosilacZalbe() {
        return new ZalbaProtivCutanja.PodnosilacZalbe();
    }

    /**
     * Create an instance of {@link TMestoDatum }
     * 
     */
    public TMestoDatum createTMestoDatum() {
        return new TMestoDatum();
    }

    /**
     * Create an instance of {@link TFIzickoLice }
     * 
     */
    public TFIzickoLice createTFIzickoLice() {
        return new TFIzickoLice();
    }

    /**
     * Create an instance of {@link TAdresa.Mesto }
     * 
     */
    public TAdresa.Mesto createTAdresaMesto() {
        return new TAdresa.Mesto();
    }

    /**
     * Create an instance of {@link TAdresa.Ulica }
     * 
     */
    public TAdresa.Ulica createTAdresaUlica() {
        return new TAdresa.Ulica();
    }

    /**
     * Create an instance of {@link TAdresa.Broj }
     * 
     */
    public TAdresa.Broj createTAdresaBroj() {
        return new TAdresa.Broj();
    }

    /**
     * Create an instance of {@link TTekst.P }
     * 
     */
    public TTekst.P createTTekstP() {
        return new TTekst.P();
    }

    /**
     * Create an instance of {@link ZalbaProtivCutanja.DetaljiZalbe.Datum }
     * 
     */
    public ZalbaProtivCutanja.DetaljiZalbe.Datum createZalbaProtivCutanjaDetaljiZalbeDatum() {
        return new ZalbaProtivCutanja.DetaljiZalbe.Datum();
    }

    /**
     * Create an instance of {@link ZalbaProtivCutanja.DetaljiZalbe.PodaciOZalbi }
     * 
     */
    public ZalbaProtivCutanja.DetaljiZalbe.PodaciOZalbi createZalbaProtivCutanjaDetaljiZalbePodaciOZalbi() {
        return new ZalbaProtivCutanja.DetaljiZalbe.PodaciOZalbi();
    }

    /**
     * Create an instance of {@link ZalbaProtivCutanja.InformacijeOZalbi.NazivOrgana }
     * 
     */
    public ZalbaProtivCutanja.InformacijeOZalbi.NazivOrgana createZalbaProtivCutanjaInformacijeOZalbiNazivOrgana() {
        return new ZalbaProtivCutanja.InformacijeOZalbi.NazivOrgana();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "zalba_protiv_cutanja", name = "naslov", scope = ZalbaProtivCutanja.InformacijeOZalbi.class)
    public JAXBElement<String> createZalbaProtivCutanjaInformacijeOZalbiNaslov(String value) {
        return new JAXBElement<String>(_ZalbaProtivCutanjaInformacijeOZalbiNaslov_QNAME, String.class, ZalbaProtivCutanja.InformacijeOZalbi.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ZalbaProtivCutanja.InformacijeOZalbi.NazivOrgana }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "zalba_protiv_cutanja", name = "naziv_organa", scope = ZalbaProtivCutanja.InformacijeOZalbi.class)
    public JAXBElement<ZalbaProtivCutanja.InformacijeOZalbi.NazivOrgana> createZalbaProtivCutanjaInformacijeOZalbiNazivOrgana(ZalbaProtivCutanja.InformacijeOZalbi.NazivOrgana value) {
        return new JAXBElement<ZalbaProtivCutanja.InformacijeOZalbi.NazivOrgana>(_ZalbaProtivCutanjaInformacijeOZalbiNazivOrgana_QNAME, ZalbaProtivCutanja.InformacijeOZalbi.NazivOrgana.class, ZalbaProtivCutanja.InformacijeOZalbi.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "zalba_protiv_cutanja", name = "zakon", scope = ZalbaProtivCutanja.InformacijeOZalbi.class)
    public JAXBElement<String> createZalbaProtivCutanjaInformacijeOZalbiZakon(String value) {
        return new JAXBElement<String>(_ZalbaProtivCutanjaInformacijeOZalbiZakon_QNAME, String.class, ZalbaProtivCutanja.InformacijeOZalbi.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TAdresa }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "zalba_protiv_cutanja", name = "Adresa", scope = TLice.class)
    public JAXBElement<TAdresa> createTLiceAdresa(TAdresa value) {
        return new JAXBElement<TAdresa>(_TLiceAdresa_QNAME, TAdresa.class, TLice.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTekst.P }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "zalba_protiv_cutanja", name = "p", scope = TTekst.class)
    public JAXBElement<TTekst.P> createTTekstP(TTekst.P value) {
        return new JAXBElement<TTekst.P>(_TTekstP_QNAME, TTekst.P.class, TTekst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "zalba_protiv_cutanja", name = "datum", scope = TMestoDatum.class)
    public JAXBElement<String> createTMestoDatumDatum(String value) {
        return new JAXBElement<String>(_TMestoDatumDatum_QNAME, String.class, TMestoDatum.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "zalba_protiv_cutanja", name = "mesto", scope = TMestoDatum.class)
    public JAXBElement<String> createTMestoDatumMesto(String value) {
        return new JAXBElement<String>(_TMestoDatumMesto_QNAME, String.class, TMestoDatum.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ZalbaProtivCutanja.InformacijeOZalbi }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "zalba_protiv_cutanja", name = "informacije_o_zalbi", scope = ZalbaProtivCutanja.class)
    public JAXBElement<ZalbaProtivCutanja.InformacijeOZalbi> createZalbaProtivCutanjaInformacijeOZalbi(ZalbaProtivCutanja.InformacijeOZalbi value) {
        return new JAXBElement<ZalbaProtivCutanja.InformacijeOZalbi>(_ZalbaProtivCutanjaInformacijeOZalbi_QNAME, ZalbaProtivCutanja.InformacijeOZalbi.class, ZalbaProtivCutanja.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ZalbaProtivCutanja.DetaljiZalbe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "zalba_protiv_cutanja", name = "detalji_zalbe", scope = ZalbaProtivCutanja.class)
    public JAXBElement<ZalbaProtivCutanja.DetaljiZalbe> createZalbaProtivCutanjaDetaljiZalbe(ZalbaProtivCutanja.DetaljiZalbe value) {
        return new JAXBElement<ZalbaProtivCutanja.DetaljiZalbe>(_ZalbaProtivCutanjaDetaljiZalbe_QNAME, ZalbaProtivCutanja.DetaljiZalbe.class, ZalbaProtivCutanja.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TPravnoLice }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "zalba_protiv_cutanja", name = "primaoc_zalbe", scope = ZalbaProtivCutanja.class)
    public JAXBElement<TPravnoLice> createZalbaProtivCutanjaPrimaocZalbe(TPravnoLice value) {
        return new JAXBElement<TPravnoLice>(_ZalbaProtivCutanjaPrimaocZalbe_QNAME, TPravnoLice.class, ZalbaProtivCutanja.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "zalba_protiv_cutanja", name = "razlog_zalbe", scope = ZalbaProtivCutanja.class)
    public JAXBElement<String> createZalbaProtivCutanjaRazlogZalbe(String value) {
        return new JAXBElement<String>(_ZalbaProtivCutanjaRazlogZalbe_QNAME, String.class, ZalbaProtivCutanja.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "zalba_protiv_cutanja", name = "napomena", scope = ZalbaProtivCutanja.class)
    public JAXBElement<String> createZalbaProtivCutanjaNapomena(String value) {
        return new JAXBElement<String>(_ZalbaProtivCutanjaNapomena_QNAME, String.class, ZalbaProtivCutanja.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TMestoDatum }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "zalba_protiv_cutanja", name = "mesto_i_datum", scope = ZalbaProtivCutanja.class)
    public JAXBElement<TMestoDatum> createZalbaProtivCutanjaMestoIDatum(TMestoDatum value) {
        return new JAXBElement<TMestoDatum>(_ZalbaProtivCutanjaMestoIDatum_QNAME, TMestoDatum.class, ZalbaProtivCutanja.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ZalbaProtivCutanja.PodnosilacZalbe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "zalba_protiv_cutanja", name = "podnosilac_zalbe", scope = ZalbaProtivCutanja.class)
    public JAXBElement<ZalbaProtivCutanja.PodnosilacZalbe> createZalbaProtivCutanjaPodnosilacZalbe(ZalbaProtivCutanja.PodnosilacZalbe value) {
        return new JAXBElement<ZalbaProtivCutanja.PodnosilacZalbe>(_ZalbaProtivCutanjaPodnosilacZalbe_QNAME, ZalbaProtivCutanja.PodnosilacZalbe.class, ZalbaProtivCutanja.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TId }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "zalba_protiv_cutanja", name = "id", scope = ZalbaProtivCutanja.class)
    public JAXBElement<TId> createZalbaProtivCutanjaId(TId value) {
        return new JAXBElement<TId>(_ZalbaProtivCutanjaId_QNAME, TId.class, ZalbaProtivCutanja.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "zalba_protiv_cutanja", name = "predlog_resenja", scope = ZalbaProtivCutanja.class)
    public JAXBElement<String> createZalbaProtivCutanjaPredlogResenja(String value) {
        return new JAXBElement<String>(_ZalbaProtivCutanjaPredlogResenja_QNAME, String.class, ZalbaProtivCutanja.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "zalba_protiv_cutanja", name = "vrsta_zalbe", scope = ZalbaProtivCutanja.class)
    public JAXBElement<String> createZalbaProtivCutanjaVrstaZalbe(String value) {
        return new JAXBElement<String>(_ZalbaProtivCutanjaVrstaZalbe_QNAME, String.class, ZalbaProtivCutanja.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TAdresa.Ulica }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "zalba_protiv_cutanja", name = "ulica", scope = TAdresa.class)
    public JAXBElement<TAdresa.Ulica> createTAdresaUlica(TAdresa.Ulica value) {
        return new JAXBElement<TAdresa.Ulica>(_TAdresaUlica_QNAME, TAdresa.Ulica.class, TAdresa.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TAdresa.Broj }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "zalba_protiv_cutanja", name = "broj", scope = TAdresa.class)
    public JAXBElement<TAdresa.Broj> createTAdresaBroj(TAdresa.Broj value) {
        return new JAXBElement<TAdresa.Broj>(_TAdresaBroj_QNAME, TAdresa.Broj.class, TAdresa.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TAdresa.Mesto }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "zalba_protiv_cutanja", name = "mesto", scope = TAdresa.class)
    public JAXBElement<TAdresa.Mesto> createTAdresaMesto(TAdresa.Mesto value) {
        return new JAXBElement<TAdresa.Mesto>(_TMestoDatumMesto_QNAME, TAdresa.Mesto.class, TAdresa.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ZalbaProtivCutanja.DetaljiZalbe.Datum }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "zalba_protiv_cutanja", name = "datum", scope = ZalbaProtivCutanja.DetaljiZalbe.class)
    public JAXBElement<ZalbaProtivCutanja.DetaljiZalbe.Datum> createZalbaProtivCutanjaDetaljiZalbeDatum(ZalbaProtivCutanja.DetaljiZalbe.Datum value) {
        return new JAXBElement<ZalbaProtivCutanja.DetaljiZalbe.Datum>(_TMestoDatumDatum_QNAME, ZalbaProtivCutanja.DetaljiZalbe.Datum.class, ZalbaProtivCutanja.DetaljiZalbe.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ZalbaProtivCutanja.DetaljiZalbe.PodaciOZalbi }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "zalba_protiv_cutanja", name = "podaci_o_zalbi", scope = ZalbaProtivCutanja.DetaljiZalbe.class)
    public JAXBElement<ZalbaProtivCutanja.DetaljiZalbe.PodaciOZalbi> createZalbaProtivCutanjaDetaljiZalbePodaciOZalbi(ZalbaProtivCutanja.DetaljiZalbe.PodaciOZalbi value) {
        return new JAXBElement<ZalbaProtivCutanja.DetaljiZalbe.PodaciOZalbi>(_ZalbaProtivCutanjaDetaljiZalbePodaciOZalbi_QNAME, ZalbaProtivCutanja.DetaljiZalbe.PodaciOZalbi.class, ZalbaProtivCutanja.DetaljiZalbe.class, value);
    }

}
