//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.30 at 02:02:10 AM CET 
//


package rs.ac.uns.ftn.portal_organa_vlasti.model.obavestenje;

import java.util.HashMap;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="informacije_o_obavestenju" type="{http://www.ftn.uns.ac.rs/obavestenje}TInformacijeOZalbi"/>
 *         &lt;element name="naslov" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tekst_obavestenja" type="{http://www.ftn.uns.ac.rs/obavestenje}TTekstObavestenja"/>
 *         &lt;element name="potpis" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="userId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="datum" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="about" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;anyAttribute processContents='lax'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "informacijeOObavestenju",
    "naslov",
    "tekstObavestenja",
    "potpis"
})
@XmlRootElement(name = "obavestenje", namespace = "http://www.ftn.uns.ac.rs/obavestenje")
public class Obavestenje {

    @XmlElement(name = "informacije_o_obavestenju", namespace = "http://www.ftn.uns.ac.rs/obavestenje", required = true)
    protected TInformacijeOZalbi informacijeOObavestenju;
    @XmlElement(namespace = "http://www.ftn.uns.ac.rs/obavestenje", required = true)
    protected String naslov;
    @XmlElement(name = "tekst_obavestenja", namespace = "http://www.ftn.uns.ac.rs/obavestenje", required = true)
    protected TTekstObavestenja tekstObavestenja;
    @XmlElement(namespace = "http://www.ftn.uns.ac.rs/obavestenje", required = true)
    protected String potpis;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "userId")
    protected String userId;
    @XmlAttribute(name = "datum")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datum;
    @XmlAttribute(name = "about")
    protected String about;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the informacijeOObavestenju property.
     * 
     * @return
     *     possible object is
     *     {@link TInformacijeOZalbi }
     *     
     */
    public TInformacijeOZalbi getInformacijeOObavestenju() {
        return informacijeOObavestenju;
    }

    /**
     * Sets the value of the informacijeOObavestenju property.
     * 
     * @param value
     *     allowed object is
     *     {@link TInformacijeOZalbi }
     *     
     */
    public void setInformacijeOObavestenju(TInformacijeOZalbi value) {
        this.informacijeOObavestenju = value;
    }

    /**
     * Gets the value of the naslov property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNaslov() {
        return naslov;
    }

    /**
     * Sets the value of the naslov property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNaslov(String value) {
        this.naslov = value;
    }

    /**
     * Gets the value of the tekstObavestenja property.
     * 
     * @return
     *     possible object is
     *     {@link TTekstObavestenja }
     *     
     */
    public TTekstObavestenja getTekstObavestenja() {
        return tekstObavestenja;
    }

    /**
     * Sets the value of the tekstObavestenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTekstObavestenja }
     *     
     */
    public void setTekstObavestenja(TTekstObavestenja value) {
        this.tekstObavestenja = value;
    }

    /**
     * Gets the value of the potpis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPotpis() {
        return potpis;
    }

    /**
     * Sets the value of the potpis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPotpis(String value) {
        this.potpis = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the userId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserId(String value) {
        this.userId = value;
    }

    /**
     * Gets the value of the datum property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatum() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatum(XMLGregorianCalendar value) {
        this.datum = value;
    }

    /**
     * Gets the value of the about property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbout() {
        return about;
    }

    /**
     * Sets the value of the about property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbout(String value) {
        this.about = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
