//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.30 at 03:11:34 AM CET 
//


package rs.ac.uns.ftn.portal_organa_vlasti.model.obavestenje;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.portal_organa_vlasti.model.obavestenje package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TPravnoLiceNazivOrgana_QNAME = new QName("http://www.ftn.uns.ac.rs/types", "naziv_organa");
    private final static QName _TPravnoLiceAdresa_QNAME = new QName("http://www.ftn.uns.ac.rs/types", "adresa");
    private final static QName _TAdresaBroj_QNAME = new QName("http://www.ftn.uns.ac.rs/types", "broj");
    private final static QName _TAdresaUlica_QNAME = new QName("http://www.ftn.uns.ac.rs/types", "ulica");
    private final static QName _TAdresaMesto_QNAME = new QName("http://www.ftn.uns.ac.rs/types", "mesto");
    private final static QName _TMestoDatumDatum_QNAME = new QName("http://www.ftn.uns.ac.rs/types", "datum");
    private final static QName _TMestoUvidaBrojKancelarije_QNAME = new QName("http://www.ftn.uns.ac.rs/obavestenje", "broj_kancelarije");
    private final static QName _TMestoUvidaAdresa_QNAME = new QName("http://www.ftn.uns.ac.rs/obavestenje", "adresa");
    private final static QName _TVremeUvidaSati_QNAME = new QName("http://www.ftn.uns.ac.rs/obavestenje", "sati");
    private final static QName _TVremeUvidaOd_QNAME = new QName("http://www.ftn.uns.ac.rs/obavestenje", "od");
    private final static QName _TVremeUvidaDo_QNAME = new QName("http://www.ftn.uns.ac.rs/obavestenje", "do");
    private final static QName _TFIzickoLicePotpis_QNAME = new QName("http://www.ftn.uns.ac.rs/types", "potpis");
    private final static QName _TFIzickoLiceIme_QNAME = new QName("http://www.ftn.uns.ac.rs/types", "ime");
    private final static QName _TFIzickoLicePrezime_QNAME = new QName("http://www.ftn.uns.ac.rs/types", "prezime");
    private final static QName _TFIzickoLiceDrugiPodaciZaKontakt_QNAME = new QName("http://www.ftn.uns.ac.rs/types", "drugi_podaci_za_kontakt");
    private final static QName _TTekstP_QNAME = new QName("http://www.ftn.uns.ac.rs/types", "p");
    private final static QName _TInformacijeOZalbiPodnosilacZahteva_QNAME = new QName("http://www.ftn.uns.ac.rs/obavestenje", "podnosilac_zahteva");
    private final static QName _TInformacijeOZalbiBrojPredmeta_QNAME = new QName("http://www.ftn.uns.ac.rs/obavestenje", "broj_predmeta");
    private final static QName _TInformacijeOZalbiOrganVlasti_QNAME = new QName("http://www.ftn.uns.ac.rs/obavestenje", "organ_vlasti");
    private final static QName _TInformacijeOZalbiDatumObavestenja_QNAME = new QName("http://www.ftn.uns.ac.rs/obavestenje", "datum_obavestenja");
    private final static QName _TTekstObavestenjaTroskovi_QNAME = new QName("http://www.ftn.uns.ac.rs/obavestenje", "troskovi");
    private final static QName _TTekstObavestenjaDatumUvida_QNAME = new QName("http://www.ftn.uns.ac.rs/obavestenje", "datum_uvida");
    private final static QName _TTekstObavestenjaMestoUvida_QNAME = new QName("http://www.ftn.uns.ac.rs/obavestenje", "mesto_uvida");
    private final static QName _TTekstObavestenjaOpisTrazeneInformacije_QNAME = new QName("http://www.ftn.uns.ac.rs/obavestenje", "opis_trazene_informacije");
    private final static QName _TTekstObavestenjaVremeUvida_QNAME = new QName("http://www.ftn.uns.ac.rs/obavestenje", "vreme_uvida");
    private final static QName _TTekstObavestenjaDatumZahteva_QNAME = new QName("http://www.ftn.uns.ac.rs/obavestenje", "datum_zahteva");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.portal_organa_vlasti.model.obavestenje
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TFIzickoLice }
     * 
     */
    public TFIzickoLice createTFIzickoLice() {
        return new TFIzickoLice();
    }

    /**
     * Create an instance of {@link TPravnoLice }
     * 
     */
    public TPravnoLice createTPravnoLice() {
        return new TPravnoLice();
    }

    /**
     * Create an instance of {@link TAdresa }
     * 
     */
    public TAdresa createTAdresa() {
        return new TAdresa();
    }

    /**
     * Create an instance of {@link TMestoDatum }
     * 
     */
    public TMestoDatum createTMestoDatum() {
        return new TMestoDatum();
    }

    /**
     * Create an instance of {@link TTekst }
     * 
     */
    public TTekst createTTekst() {
        return new TTekst();
    }

    /**
     * Create an instance of {@link TInformacijeOZalbi }
     * 
     */
    public TInformacijeOZalbi createTInformacijeOZalbi() {
        return new TInformacijeOZalbi();
    }

    /**
     * Create an instance of {@link Obavestenje }
     * 
     */
    public Obavestenje createObavestenje() {
        return new Obavestenje();
    }

    /**
     * Create an instance of {@link TTekstObavestenja }
     * 
     */
    public TTekstObavestenja createTTekstObavestenja() {
        return new TTekstObavestenja();
    }

    /**
     * Create an instance of {@link TVremeUvida }
     * 
     */
    public TVremeUvida createTVremeUvida() {
        return new TVremeUvida();
    }

    /**
     * Create an instance of {@link TMestoUvida }
     * 
     */
    public TMestoUvida createTMestoUvida() {
        return new TMestoUvida();
    }

    /**
     * Create an instance of {@link TId }
     * 
     */
    public TId createTId() {
        return new TId();
    }

    /**
     * Create an instance of {@link TFIzickoLice.Ime }
     * 
     */
    public TFIzickoLice.Ime createTFIzickoLiceIme() {
        return new TFIzickoLice.Ime();
    }

    /**
     * Create an instance of {@link TFIzickoLice.Prezime }
     * 
     */
    public TFIzickoLice.Prezime createTFIzickoLicePrezime() {
        return new TFIzickoLice.Prezime();
    }

    /**
     * Create an instance of {@link TFIzickoLice.DrugiPodaciZaKontakt }
     * 
     */
    public TFIzickoLice.DrugiPodaciZaKontakt createTFIzickoLiceDrugiPodaciZaKontakt() {
        return new TFIzickoLice.DrugiPodaciZaKontakt();
    }

    /**
     * Create an instance of {@link TPravnoLice.NazivOrgana }
     * 
     */
    public TPravnoLice.NazivOrgana createTPravnoLiceNazivOrgana() {
        return new TPravnoLice.NazivOrgana();
    }

    /**
     * Create an instance of {@link TAdresa.Mesto }
     * 
     */
    public TAdresa.Mesto createTAdresaMesto() {
        return new TAdresa.Mesto();
    }

    /**
     * Create an instance of {@link TAdresa.Ulica }
     * 
     */
    public TAdresa.Ulica createTAdresaUlica() {
        return new TAdresa.Ulica();
    }

    /**
     * Create an instance of {@link TAdresa.Broj }
     * 
     */
    public TAdresa.Broj createTAdresaBroj() {
        return new TAdresa.Broj();
    }

    /**
     * Create an instance of {@link TMestoDatum.Mesto }
     * 
     */
    public TMestoDatum.Mesto createTMestoDatumMesto() {
        return new TMestoDatum.Mesto();
    }

    /**
     * Create an instance of {@link TMestoDatum.Datum }
     * 
     */
    public TMestoDatum.Datum createTMestoDatumDatum() {
        return new TMestoDatum.Datum();
    }

    /**
     * Create an instance of {@link TTekst.P }
     * 
     */
    public TTekst.P createTTekstP() {
        return new TTekst.P();
    }

    /**
     * Create an instance of {@link TInformacijeOZalbi.BrojPredmeta }
     * 
     */
    public TInformacijeOZalbi.BrojPredmeta createTInformacijeOZalbiBrojPredmeta() {
        return new TInformacijeOZalbi.BrojPredmeta();
    }

    /**
     * Create an instance of {@link TInformacijeOZalbi.DatumObavestenja }
     * 
     */
    public TInformacijeOZalbi.DatumObavestenja createTInformacijeOZalbiDatumObavestenja() {
        return new TInformacijeOZalbi.DatumObavestenja();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TPravnoLice.NazivOrgana }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "naziv_organa", scope = TPravnoLice.class)
    public JAXBElement<TPravnoLice.NazivOrgana> createTPravnoLiceNazivOrgana(TPravnoLice.NazivOrgana value) {
        return new JAXBElement<TPravnoLice.NazivOrgana>(_TPravnoLiceNazivOrgana_QNAME, TPravnoLice.NazivOrgana.class, TPravnoLice.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TAdresa }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "adresa", scope = TPravnoLice.class)
    public JAXBElement<TAdresa> createTPravnoLiceAdresa(TAdresa value) {
        return new JAXBElement<TAdresa>(_TPravnoLiceAdresa_QNAME, TAdresa.class, TPravnoLice.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TAdresa.Broj }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "broj", scope = TAdresa.class)
    public JAXBElement<TAdresa.Broj> createTAdresaBroj(TAdresa.Broj value) {
        return new JAXBElement<TAdresa.Broj>(_TAdresaBroj_QNAME, TAdresa.Broj.class, TAdresa.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TAdresa.Ulica }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "ulica", scope = TAdresa.class)
    public JAXBElement<TAdresa.Ulica> createTAdresaUlica(TAdresa.Ulica value) {
        return new JAXBElement<TAdresa.Ulica>(_TAdresaUlica_QNAME, TAdresa.Ulica.class, TAdresa.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TAdresa.Mesto }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "mesto", scope = TAdresa.class)
    public JAXBElement<TAdresa.Mesto> createTAdresaMesto(TAdresa.Mesto value) {
        return new JAXBElement<TAdresa.Mesto>(_TAdresaMesto_QNAME, TAdresa.Mesto.class, TAdresa.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TMestoDatum.Datum }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "datum", scope = TMestoDatum.class)
    public JAXBElement<TMestoDatum.Datum> createTMestoDatumDatum(TMestoDatum.Datum value) {
        return new JAXBElement<TMestoDatum.Datum>(_TMestoDatumDatum_QNAME, TMestoDatum.Datum.class, TMestoDatum.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TMestoDatum.Mesto }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "mesto", scope = TMestoDatum.class)
    public JAXBElement<TMestoDatum.Mesto> createTMestoDatumMesto(TMestoDatum.Mesto value) {
        return new JAXBElement<TMestoDatum.Mesto>(_TAdresaMesto_QNAME, TMestoDatum.Mesto.class, TMestoDatum.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/obavestenje", name = "broj_kancelarije", scope = TMestoUvida.class)
    public JAXBElement<BigInteger> createTMestoUvidaBrojKancelarije(BigInteger value) {
        return new JAXBElement<BigInteger>(_TMestoUvidaBrojKancelarije_QNAME, BigInteger.class, TMestoUvida.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TAdresa }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/obavestenje", name = "adresa", scope = TMestoUvida.class)
    public JAXBElement<TAdresa> createTMestoUvidaAdresa(TAdresa value) {
        return new JAXBElement<TAdresa>(_TMestoUvidaAdresa_QNAME, TAdresa.class, TMestoUvida.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/obavestenje", name = "sati", scope = TVremeUvida.class)
    public JAXBElement<String> createTVremeUvidaSati(String value) {
        return new JAXBElement<String>(_TVremeUvidaSati_QNAME, String.class, TVremeUvida.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/obavestenje", name = "od", scope = TVremeUvida.class)
    public JAXBElement<String> createTVremeUvidaOd(String value) {
        return new JAXBElement<String>(_TVremeUvidaOd_QNAME, String.class, TVremeUvida.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/obavestenje", name = "do", scope = TVremeUvida.class)
    public JAXBElement<String> createTVremeUvidaDo(String value) {
        return new JAXBElement<String>(_TVremeUvidaDo_QNAME, String.class, TVremeUvida.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "potpis", scope = TFIzickoLice.class)
    public JAXBElement<String> createTFIzickoLicePotpis(String value) {
        return new JAXBElement<String>(_TFIzickoLicePotpis_QNAME, String.class, TFIzickoLice.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TFIzickoLice.Ime }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "ime", scope = TFIzickoLice.class)
    public JAXBElement<TFIzickoLice.Ime> createTFIzickoLiceIme(TFIzickoLice.Ime value) {
        return new JAXBElement<TFIzickoLice.Ime>(_TFIzickoLiceIme_QNAME, TFIzickoLice.Ime.class, TFIzickoLice.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TFIzickoLice.Prezime }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "prezime", scope = TFIzickoLice.class)
    public JAXBElement<TFIzickoLice.Prezime> createTFIzickoLicePrezime(TFIzickoLice.Prezime value) {
        return new JAXBElement<TFIzickoLice.Prezime>(_TFIzickoLicePrezime_QNAME, TFIzickoLice.Prezime.class, TFIzickoLice.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TFIzickoLice.DrugiPodaciZaKontakt }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "drugi_podaci_za_kontakt", scope = TFIzickoLice.class)
    public JAXBElement<TFIzickoLice.DrugiPodaciZaKontakt> createTFIzickoLiceDrugiPodaciZaKontakt(TFIzickoLice.DrugiPodaciZaKontakt value) {
        return new JAXBElement<TFIzickoLice.DrugiPodaciZaKontakt>(_TFIzickoLiceDrugiPodaciZaKontakt_QNAME, TFIzickoLice.DrugiPodaciZaKontakt.class, TFIzickoLice.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TAdresa }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "adresa", scope = TFIzickoLice.class)
    public JAXBElement<TAdresa> createTFIzickoLiceAdresa(TAdresa value) {
        return new JAXBElement<TAdresa>(_TPravnoLiceAdresa_QNAME, TAdresa.class, TFIzickoLice.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTekst.P }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/types", name = "p", scope = TTekst.class)
    public JAXBElement<TTekst.P> createTTekstP(TTekst.P value) {
        return new JAXBElement<TTekst.P>(_TTekstP_QNAME, TTekst.P.class, TTekst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TFIzickoLice }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/obavestenje", name = "podnosilac_zahteva", scope = TInformacijeOZalbi.class)
    public JAXBElement<TFIzickoLice> createTInformacijeOZalbiPodnosilacZahteva(TFIzickoLice value) {
        return new JAXBElement<TFIzickoLice>(_TInformacijeOZalbiPodnosilacZahteva_QNAME, TFIzickoLice.class, TInformacijeOZalbi.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TInformacijeOZalbi.BrojPredmeta }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/obavestenje", name = "broj_predmeta", scope = TInformacijeOZalbi.class)
    public JAXBElement<TInformacijeOZalbi.BrojPredmeta> createTInformacijeOZalbiBrojPredmeta(TInformacijeOZalbi.BrojPredmeta value) {
        return new JAXBElement<TInformacijeOZalbi.BrojPredmeta>(_TInformacijeOZalbiBrojPredmeta_QNAME, TInformacijeOZalbi.BrojPredmeta.class, TInformacijeOZalbi.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TPravnoLice }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/obavestenje", name = "organ_vlasti", scope = TInformacijeOZalbi.class)
    public JAXBElement<TPravnoLice> createTInformacijeOZalbiOrganVlasti(TPravnoLice value) {
        return new JAXBElement<TPravnoLice>(_TInformacijeOZalbiOrganVlasti_QNAME, TPravnoLice.class, TInformacijeOZalbi.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TInformacijeOZalbi.DatumObavestenja }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/obavestenje", name = "datum_obavestenja", scope = TInformacijeOZalbi.class)
    public JAXBElement<TInformacijeOZalbi.DatumObavestenja> createTInformacijeOZalbiDatumObavestenja(TInformacijeOZalbi.DatumObavestenja value) {
        return new JAXBElement<TInformacijeOZalbi.DatumObavestenja>(_TInformacijeOZalbiDatumObavestenja_QNAME, TInformacijeOZalbi.DatumObavestenja.class, TInformacijeOZalbi.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/obavestenje", name = "troskovi", scope = TTekstObavestenja.class)
    public JAXBElement<BigInteger> createTTekstObavestenjaTroskovi(BigInteger value) {
        return new JAXBElement<BigInteger>(_TTekstObavestenjaTroskovi_QNAME, BigInteger.class, TTekstObavestenja.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/obavestenje", name = "datum_uvida", scope = TTekstObavestenja.class)
    public JAXBElement<String> createTTekstObavestenjaDatumUvida(String value) {
        return new JAXBElement<String>(_TTekstObavestenjaDatumUvida_QNAME, String.class, TTekstObavestenja.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TMestoUvida }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/obavestenje", name = "mesto_uvida", scope = TTekstObavestenja.class)
    public JAXBElement<TMestoUvida> createTTekstObavestenjaMestoUvida(TMestoUvida value) {
        return new JAXBElement<TMestoUvida>(_TTekstObavestenjaMestoUvida_QNAME, TMestoUvida.class, TTekstObavestenja.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/obavestenje", name = "opis_trazene_informacije", scope = TTekstObavestenja.class)
    public JAXBElement<String> createTTekstObavestenjaOpisTrazeneInformacije(String value) {
        return new JAXBElement<String>(_TTekstObavestenjaOpisTrazeneInformacije_QNAME, String.class, TTekstObavestenja.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TVremeUvida }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/obavestenje", name = "vreme_uvida", scope = TTekstObavestenja.class)
    public JAXBElement<TVremeUvida> createTTekstObavestenjaVremeUvida(TVremeUvida value) {
        return new JAXBElement<TVremeUvida>(_TTekstObavestenjaVremeUvida_QNAME, TVremeUvida.class, TTekstObavestenja.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/obavestenje", name = "datum_zahteva", scope = TTekstObavestenja.class)
    public JAXBElement<XMLGregorianCalendar> createTTekstObavestenjaDatumZahteva(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_TTekstObavestenjaDatumZahteva_QNAME, XMLGregorianCalendar.class, TTekstObavestenja.class, value);
    }

}
